package pt.uminho.ceb.biosystems.merlin.entities.experimental;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ExperimentalDescription generated by hbm2java
 */
@Entity
@Table(name = "experimental_description")
public class ExperimentalDescription implements java.io.Serializable {

	private ExperimentalDescriptionId id;
	private ExperimentalFactor experimentalFactor;
	private String value;

	public ExperimentalDescription() {
	}

	public ExperimentalDescription(ExperimentalDescriptionId id, ExperimentalFactor experimentalFactor, String value) {
		this.id = id;
		this.experimentalFactor = experimentalFactor;
		this.value = value;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idexperiment", column = @Column(name = "idexperiment", nullable = false)),
			@AttributeOverride(name = "modelExperimentalFactorIdexperimentalFactor", column = @Column(name = "model_experimental_factor_idexperimental_factor", nullable = false)) })
	public ExperimentalDescriptionId getId() {
		return this.id;
	}

	public void setId(ExperimentalDescriptionId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_experimental_factor_idexperimental_factor", nullable = false, insertable = false, updatable = false)
	public ExperimentalFactor getExperimentalFactor() {
		return this.experimentalFactor;
	}

	public void setExperimentalFactor(ExperimentalFactor experimentalFactor) {
		this.experimentalFactor = experimentalFactor;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
