package pt.uminho.ceb.biosystems.merlin.entities.experimental;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExperimentalDescriptionId generated by hbm2java
 */
@Embeddable
public class ExperimentalDescriptionId implements java.io.Serializable {

	private int idexperiment;
	private int modelExperimentalFactorIdexperimentalFactor;

	public ExperimentalDescriptionId() {
	}

	public ExperimentalDescriptionId(int idexperiment, int modelExperimentalFactorIdexperimentalFactor) {
		this.idexperiment = idexperiment;
		this.modelExperimentalFactorIdexperimentalFactor = modelExperimentalFactorIdexperimentalFactor;
	}

	@Column(name = "idexperiment", nullable = false)
	public int getIdexperiment() {
		return this.idexperiment;
	}

	public void setIdexperiment(int idexperiment) {
		this.idexperiment = idexperiment;
	}

	@Column(name = "model_experimental_factor_idexperimental_factor", nullable = false)
	public int getModelExperimentalFactorIdexperimentalFactor() {
		return this.modelExperimentalFactorIdexperimentalFactor;
	}

	public void setModelExperimentalFactorIdexperimentalFactor(int modelExperimentalFactorIdexperimentalFactor) {
		this.modelExperimentalFactorIdexperimentalFactor = modelExperimentalFactorIdexperimentalFactor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExperimentalDescriptionId))
			return false;
		ExperimentalDescriptionId castOther = (ExperimentalDescriptionId) other;

		return (this.getIdexperiment() == castOther.getIdexperiment())
				&& (this.getModelExperimentalFactorIdexperimentalFactor() == castOther
						.getModelExperimentalFactorIdexperimentalFactor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdexperiment();
		result = 37 * result + this.getModelExperimentalFactorIdexperimentalFactor();
		return result;
	}

}
