//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 06:10:17 PM GMT 
//


package pt.uminho.ceb.biosystems.merlin.utilities.blast.ebi_blastparser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Header" type="{http://www.ebi.ac.uk/schema}tHeader"/>
 *         &lt;element name="SequenceSimilaritySearchResult" type="{http://www.ebi.ac.uk/schema}tSSSR"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "EBIApplicationResult")
public class EBIApplicationResult {

    @XmlElement(name = "Header", required = true)
    protected THeader header;
    @XmlElement(name = "SequenceSimilaritySearchResult", required = true)
    protected TSSSR sequenceSimilaritySearchResult;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link THeader }
     *     
     */
    public THeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link THeader }
     *     
     */
    public void setHeader(THeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the sequenceSimilaritySearchResult property.
     * 
     * @return
     *     possible object is
     *     {@link TSSSR }
     *     
     */
    public TSSSR getSequenceSimilaritySearchResult() {
        return sequenceSimilaritySearchResult;
    }

    /**
     * Sets the value of the sequenceSimilaritySearchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSSSR }
     *     
     */
    public void setSequenceSimilaritySearchResult(TSSSR value) {
        this.sequenceSimilaritySearchResult = value;
    }

}
