//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.06 at 11:51:44 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ebi.ac.uk/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pt.uminho.ceb.biosystems.merlin.utilities.blast.ebi_blastparser;
