//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 06:10:17 PM GMT 
//


package pt.uminho.ceb.biosystems.merlin.utilities.blast.ebi_blastparser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="program" type="{http://www.ebi.ac.uk/schema}tProgram"/>
 *         &lt;element name="commandLine" type="{http://www.ebi.ac.uk/schema}tCmdLine" minOccurs="0"/>
 *         &lt;element name="parameters" type="{http://www.ebi.ac.uk/schema}tParameters"/>
 *         &lt;element name="timeInfo" type="{http://www.ebi.ac.uk/schema}tTimeInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tHeader", propOrder = {
    "program",
    "commandLine",
    "parameters",
    "timeInfo"
})
public class THeader {

    @XmlElement(required = true)
    protected TProgram program;
    protected TCmdLine commandLine;
    @XmlElement(required = true)
    protected TParameters parameters;
    protected TTimeInfo timeInfo;

    /**
     * Gets the value of the program property.
     * 
     * @return
     *     possible object is
     *     {@link TProgram }
     *     
     */
    public TProgram getProgram() {
        return program;
    }

    /**
     * Sets the value of the program property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProgram }
     *     
     */
    public void setProgram(TProgram value) {
        this.program = value;
    }

    /**
     * Gets the value of the commandLine property.
     * 
     * @return
     *     possible object is
     *     {@link TCmdLine }
     *     
     */
    public TCmdLine getCommandLine() {
        return commandLine;
    }

    /**
     * Sets the value of the commandLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCmdLine }
     *     
     */
    public void setCommandLine(TCmdLine value) {
        this.commandLine = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link TParameters }
     *     
     */
    public TParameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link TParameters }
     *     
     */
    public void setParameters(TParameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the timeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TTimeInfo }
     *     
     */
    public TTimeInfo getTimeInfo() {
        return timeInfo;
    }

    /**
     * Sets the value of the timeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTimeInfo }
     *     
     */
    public void setTimeInfo(TTimeInfo value) {
        this.timeInfo = value;
    }

}
