//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.06 at 11:51:44 AM BST 
//


package pt.uminho.ceb.biosystems.merlin.utilities.blast.ebi_blastparser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="sequences" type="{http://www.ebi.ac.uk/schema}tSequences"/&gt;
 *         &lt;element name="databases" type="{http://www.ebi.ac.uk/schema}tDatabases" minOccurs="0"/&gt;
 *         &lt;element name="matrix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktup" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="sort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="scores" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="strand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="filter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="histogram" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="alignments" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="statistics" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gapOpen" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="gapExtension" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="sequenceRange" type="{http://www.ebi.ac.uk/schema}tRange" minOccurs="0"/&gt;
 *         &lt;element name="databaseRange" type="{http://www.ebi.ac.uk/schema}tRange" minOccurs="0"/&gt;
 *         &lt;element name="moleculeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="expectationUpper" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="expectationLower" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tParameters", propOrder = {

})
public class TParameters {

    @XmlElement(required = true)
    protected TSequences sequences;
    protected TDatabases databases;
    protected String matrix;
    protected Integer ktup;
    protected String sort;
    protected Integer scores;
    protected String strand;
    protected String filter;
    protected Boolean histogram;
    protected Integer alignments;
    protected String statistics;
    protected Float gapOpen;
    protected Float gapExtension;
    protected String sequenceRange;
    protected String databaseRange;
    protected String moleculeType;
    protected String expectationUpper;
    protected String expectationLower;

    /**
     * Gets the value of the sequences property.
     * 
     * @return
     *     possible object is
     *     {@link TSequences }
     *     
     */
    public TSequences getSequences() {
        return sequences;
    }

    /**
     * Sets the value of the sequences property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSequences }
     *     
     */
    public void setSequences(TSequences value) {
        this.sequences = value;
    }

    /**
     * Gets the value of the databases property.
     * 
     * @return
     *     possible object is
     *     {@link TDatabases }
     *     
     */
    public TDatabases getDatabases() {
        return databases;
    }

    /**
     * Sets the value of the databases property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatabases }
     *     
     */
    public void setDatabases(TDatabases value) {
        this.databases = value;
    }

    /**
     * Gets the value of the matrix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatrix() {
        return matrix;
    }

    /**
     * Sets the value of the matrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatrix(String value) {
        this.matrix = value;
    }

    /**
     * Gets the value of the ktup property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKtup() {
        return ktup;
    }

    /**
     * Sets the value of the ktup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKtup(Integer value) {
        this.ktup = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSort(String value) {
        this.sort = value;
    }

    /**
     * Gets the value of the scores property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScores() {
        return scores;
    }

    /**
     * Sets the value of the scores property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScores(Integer value) {
        this.scores = value;
    }

    /**
     * Gets the value of the strand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrand() {
        return strand;
    }

    /**
     * Sets the value of the strand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrand(String value) {
        this.strand = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilter(String value) {
        this.filter = value;
    }

    /**
     * Gets the value of the histogram property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHistogram() {
        return histogram;
    }

    /**
     * Sets the value of the histogram property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHistogram(Boolean value) {
        this.histogram = value;
    }

    /**
     * Gets the value of the alignments property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAlignments() {
        return alignments;
    }

    /**
     * Sets the value of the alignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAlignments(Integer value) {
        this.alignments = value;
    }

    /**
     * Gets the value of the statistics property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatistics() {
        return statistics;
    }

    /**
     * Sets the value of the statistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatistics(String value) {
        this.statistics = value;
    }

    /**
     * Gets the value of the gapOpen property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getGapOpen() {
        return gapOpen;
    }

    /**
     * Sets the value of the gapOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGapOpen(Float value) {
        this.gapOpen = value;
    }

    /**
     * Gets the value of the gapExtension property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getGapExtension() {
        return gapExtension;
    }

    /**
     * Sets the value of the gapExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGapExtension(Float value) {
        this.gapExtension = value;
    }

    /**
     * Gets the value of the sequenceRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceRange() {
        return sequenceRange;
    }

    /**
     * Sets the value of the sequenceRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceRange(String value) {
        this.sequenceRange = value;
    }

    /**
     * Gets the value of the databaseRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseRange() {
        return databaseRange;
    }

    /**
     * Sets the value of the databaseRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseRange(String value) {
        this.databaseRange = value;
    }

    /**
     * Gets the value of the moleculeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoleculeType() {
        return moleculeType;
    }

    /**
     * Sets the value of the moleculeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoleculeType(String value) {
        this.moleculeType = value;
    }

    /**
     * Gets the value of the expectationUpper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpectationUpper() {
        return expectationUpper;
    }

    /**
     * Sets the value of the expectationUpper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpectationUpper(String value) {
        this.expectationUpper = value;
    }

    /**
     * Gets the value of the expectationLower property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpectationLower() {
        return expectationLower;
    }

    /**
     * Sets the value of the expectationLower property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpectationLower(String value) {
        this.expectationLower = value;
    }

}
