package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Aug 9, 2019 9:51:18 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * ModelModule generated by hbm2java
 */
@Entity
@Table(name = "model_module")
public class ModelModule implements java.io.Serializable {

	private int id;
	private String reaction;
	private String entryId;
	private String stoichiometry;
	private String name;
	private String definition;
	private String hieralchicalClass;
	private String type;
	private String note;
	private String gprStatus;
	private Set<ModelModuleHasOrthology> modelModuleHasOrthologies = new HashSet<ModelModuleHasOrthology>(0);
	private Set<ModelPathwayHasModule> modelPathwayHasModules = new HashSet<ModelPathwayHasModule>(0);
	private Set<ModelModuleHasModelProtein> modelModuleHasModelProteins = new HashSet<ModelModuleHasModelProtein>(0);
	private Set<ModelModulesHasCompound> modelModulesHasCompounds = new HashSet<ModelModulesHasCompound>(0);

	public ModelModule() {
	}

	public ModelModule(int id, String reaction, String entryId, String definition, String type) {
		this.id = id;
		this.reaction = reaction;
		this.entryId = entryId;
		this.definition = definition;
		this.type = type;
	}

	public ModelModule(int id, String reaction, String entryId, String stoichiometry, String name, String definition,
			String hieralchicalClass, String type, String note, String gprStatus,
			Set<ModelModuleHasOrthology> modelModuleHasOrthologies,
			Set<ModelPathwayHasModule> modelPathwayHasModules,
			Set<ModelModuleHasModelProtein> modelModuleHasModelProteins,
			Set<ModelModulesHasCompound> modelModulesHasCompounds) {
		this.id = id;
		this.reaction = reaction;
		this.entryId = entryId;
		this.stoichiometry = stoichiometry;
		this.name = name;
		this.definition = definition;
		this.hieralchicalClass = hieralchicalClass;
		this.type = type;
		this.note = note;
		this.gprStatus = gprStatus;
		this.modelModuleHasOrthologies = modelModuleHasOrthologies;
		this.modelPathwayHasModules = modelPathwayHasModules;
		this.modelModuleHasModelProteins = modelModuleHasModelProteins;
		this.modelModulesHasCompounds = modelModulesHasCompounds;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "reaction", nullable = false, columnDefinition="Text")
	public String getReaction() {
		return this.reaction;
	}

	public void setReaction(String reaction) {
		this.reaction = reaction;
	}

	@Column(name = "entry_id", nullable = false, length = 6)
	public String getEntryId() {
		return this.entryId;
	}

	public void setEntryId(String entryId) {
		this.entryId = entryId;
	}

	@Column(name = "stoichiometry", length = 45)
	public String getStoichiometry() {
		return this.stoichiometry;
	}

	public void setStoichiometry(String stoichiometry) {
		this.stoichiometry = stoichiometry;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "definition", nullable = false, length = 65535, columnDefinition="Text")
	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	@Column(name = "hieralchical_class", length = 65535, columnDefinition="Text")
	public String getHieralchicalClass() {
		return this.hieralchicalClass;
	}

	public void setHieralchicalClass(String hieralchicalClass) {
		this.hieralchicalClass = hieralchicalClass;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	@Column(name = "note", length = 45)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "gpr_status", length = 45)
	public String getGprStatus() {
		return this.gprStatus;
	}

	public void setGprStatus(String gprStatus) {
		this.gprStatus = gprStatus;
	}
	
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelModule")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelModuleHasOrthology> getModelModuleHasOrthologies() {
		return this.modelModuleHasOrthologies;
	}

	public void setModelModuleHasOrthologies(Set<ModelModuleHasOrthology> modelModuleHasOrthologies) {
		this.modelModuleHasOrthologies = modelModuleHasOrthologies;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelModule")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelPathwayHasModule> getModelPathwayHasModules() {
		return this.modelPathwayHasModules;
	}

	public void setModelPathwayHasModules(Set<ModelPathwayHasModule> modelPathwayHasModules) {
		this.modelPathwayHasModules = modelPathwayHasModules;
	}
	
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelModule")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelModuleHasModelProtein> getModelModuleHasModelProteins() {
		return this.modelModuleHasModelProteins;
	}

	public void setModelModuleHasModelProteins(Set<ModelModuleHasModelProtein> modelModuleHasModelProteins) {
		this.modelModuleHasModelProteins = modelModuleHasModelProteins;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelModule")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelModulesHasCompound> getModelModulesHasCompounds() {
		return this.modelModulesHasCompounds;
	}

	public void setModelModulesHasCompounds(Set<ModelModulesHasCompound> modelModulesHasCompounds) {
		this.modelModulesHasCompounds = modelModulesHasCompounds;
	}

}
