package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelPathwayHasCompoundId generated by hbm2java
 */
@Embeddable
public class ModelPathwayHasCompoundId implements java.io.Serializable {

	private int modelPathwayIdpathway;
	private int modelCompoundIdcompound;

	public ModelPathwayHasCompoundId() {
	}

	public ModelPathwayHasCompoundId(int modelPathwayIdpathway, int modelCompoundIdcompound) {
		this.modelPathwayIdpathway = modelPathwayIdpathway;
		this.modelCompoundIdcompound = modelCompoundIdcompound;
	}

	@Column(name = "model_pathway_idpathway", nullable = false)
	public int getModelPathwayIdpathway() {
		return this.modelPathwayIdpathway;
	}

	public void setModelPathwayIdpathway(int modelPathwayIdpathway) {
		this.modelPathwayIdpathway = modelPathwayIdpathway;
	}

	@Column(name = "model_compound_idcompound", nullable = false)
	public int getModelCompoundIdcompound() {
		return this.modelCompoundIdcompound;
	}

	public void setModelCompoundIdcompound(int modelCompoundIdcompound) {
		this.modelCompoundIdcompound = modelCompoundIdcompound;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelPathwayHasCompoundId))
			return false;
		ModelPathwayHasCompoundId castOther = (ModelPathwayHasCompoundId) other;

		return (this.getModelPathwayIdpathway() == castOther.getModelPathwayIdpathway())
				&& (this.getModelCompoundIdcompound() == castOther.getModelCompoundIdcompound());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelPathwayIdpathway();
		result = 37 * result + this.getModelCompoundIdcompound();
		return result;
	}

}
