package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ModelSequenceFeature generated by hbm2java
 */
@Entity
@Table(name = "model_sequence_feature")
public class ModelSequenceFeature implements java.io.Serializable {

	private ModelSequenceFeatureId id;
	private ModelFeature modelFeature;
	private ModelSequence modelSequence;
	private String startPositionApproximate;
	private String endPositionApproximate;

	public ModelSequenceFeature() {
	}

	public ModelSequenceFeature(ModelSequenceFeatureId id, ModelFeature modelFeature, ModelSequence modelSequence) {
		this.id = id;
		this.modelFeature = modelFeature;
		this.modelSequence = modelSequence;
	}

	public ModelSequenceFeature(ModelSequenceFeatureId id, ModelFeature modelFeature, ModelSequence modelSequence,
			String startPositionApproximate, String endPositionApproximate) {
		this.id = id;
		this.modelFeature = modelFeature;
		this.modelSequence = modelSequence;
		this.startPositionApproximate = startPositionApproximate;
		this.endPositionApproximate = endPositionApproximate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "modelSequenceIdsequence", column = @Column(name = "model_sequence_idsequence", nullable = false)),
			@AttributeOverride(name = "modelFeatureIdfeature", column = @Column(name = "model_feature_idfeature", nullable = false)) })
	public ModelSequenceFeatureId getId() {
		return this.id;
	}

	public void setId(ModelSequenceFeatureId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_feature_idfeature", nullable = false, insertable = false, updatable = false)
	public ModelFeature getModelFeature() {
		return this.modelFeature;
	}

	public void setModelFeature(ModelFeature modelFeature) {
		this.modelFeature = modelFeature;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_sequence_idsequence", nullable = false, insertable = false, updatable = false)
	public ModelSequence getModelSequence() {
		return this.modelSequence;
	}

	public void setModelSequence(ModelSequence modelSequence) {
		this.modelSequence = modelSequence;
	}

	@Column(name = "start_position_approximate", length = 20)
	public String getStartPositionApproximate() {
		return this.startPositionApproximate;
	}

	public void setStartPositionApproximate(String startPositionApproximate) {
		this.startPositionApproximate = startPositionApproximate;
	}

	@Column(name = "end_position_approximate", length = 20)
	public String getEndPositionApproximate() {
		return this.endPositionApproximate;
	}

	public void setEndPositionApproximate(String endPositionApproximate) {
		this.endPositionApproximate = endPositionApproximate;
	}

}
