package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelModuleHasOrthologyId generated by hbm2java
 */
@Embeddable
public class ModelModuleHasOrthologyId implements java.io.Serializable {

	private int modelModuleId;
	private int modelOrthologyId;

	public ModelModuleHasOrthologyId() {
	}

	public ModelModuleHasOrthologyId(int modelModuleId, int modelOrthologyId) {
		this.modelModuleId = modelModuleId;
		this.modelOrthologyId = modelOrthologyId;
	}

	@Column(name = "model_module_id", nullable = false)
	public int getModelModuleId() {
		return this.modelModuleId;
	}

	public void setModelModuleId(int modelModuleId) {
		this.modelModuleId = modelModuleId;
	}

	@Column(name = "model_orthology_id", nullable = false)
	public int getModelOrthologyId() {
		return this.modelOrthologyId;
	}

	public void setModelOrthologyId(int modelOrthologyId) {
		this.modelOrthologyId = modelOrthologyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelModuleHasOrthologyId))
			return false;
		ModelModuleHasOrthologyId castOther = (ModelModuleHasOrthologyId) other;

		return (this.getModelModuleId() == castOther.getModelModuleId())
				&& (this.getModelOrthologyId() == castOther.getModelOrthologyId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelModuleId();
		result = 37 * result + this.getModelOrthologyId();
		return result;
	}

}
