package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelSequenceFeatureId generated by hbm2java
 */
@Embeddable
public class ModelSequenceFeatureId implements java.io.Serializable {

	private int modelSequenceIdsequence;
	private int modelFeatureIdfeature;

	public ModelSequenceFeatureId() {
	}

	public ModelSequenceFeatureId(int modelSequenceIdsequence, int modelFeatureIdfeature) {
		this.modelSequenceIdsequence = modelSequenceIdsequence;
		this.modelFeatureIdfeature = modelFeatureIdfeature;
	}

	@Column(name = "model_sequence_idsequence", nullable = false)
	public int getModelSequenceIdsequence() {
		return this.modelSequenceIdsequence;
	}

	public void setModelSequenceIdsequence(int modelSequenceIdsequence) {
		this.modelSequenceIdsequence = modelSequenceIdsequence;
	}

	@Column(name = "model_feature_idfeature", nullable = false)
	public int getModelFeatureIdfeature() {
		return this.modelFeatureIdfeature;
	}

	public void setModelFeatureIdfeature(int modelFeatureIdfeature) {
		this.modelFeatureIdfeature = modelFeatureIdfeature;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelSequenceFeatureId))
			return false;
		ModelSequenceFeatureId castOther = (ModelSequenceFeatureId) other;

		return (this.getModelSequenceIdsequence() == castOther.getModelSequenceIdsequence())
				&& (this.getModelFeatureIdfeature() == castOther.getModelFeatureIdfeature());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelSequenceIdsequence();
		result = 37 * result + this.getModelFeatureIdfeature();
		return result;
	}

}
