package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Sep 11, 2019 1:12:29 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelPathwayHasModelProteinId generated by hbm2java
 */
@Embeddable
public class ModelPathwayHasModelProteinId implements java.io.Serializable {

	private int modelPathwayIdpathway;
	private int modelProteinIdprotein;

	public ModelPathwayHasModelProteinId() {
	}

	public ModelPathwayHasModelProteinId(int modelPathwayIdpathway, int modelProteinIdprotein) {
		this.modelPathwayIdpathway = modelPathwayIdpathway;
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	@Column(name = "model_pathway_idpathway", nullable = false)
	public int getModelPathwayIdpathway() {
		return this.modelPathwayIdpathway;
	}

	public void setModelPathwayIdpathway(int modelPathwayIdpathway) {
		this.modelPathwayIdpathway = modelPathwayIdpathway;
	}

	@Column(name = "model_protein_idprotein", nullable = false)
	public int getModelProteinIdprotein() {
		return this.modelProteinIdprotein;
	}

	public void setModelProteinIdprotein(int modelProteinIdprotein) {
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelPathwayHasModelProteinId))
			return false;
		ModelPathwayHasModelProteinId castOther = (ModelPathwayHasModelProteinId) other;

		return (this.getModelPathwayIdpathway() == castOther.getModelPathwayIdpathway())
				&& (this.getModelProteinIdprotein() == castOther.getModelProteinIdprotein());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelPathwayIdpathway();
		result = 37 * result + this.getModelProteinIdprotein();
		return result;
	}

}
