package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelPathwayHasEnzymeId generated by hbm2java
 */
@Embeddable
public class ModelPathwayHasEnzymeId implements java.io.Serializable {

	private int pathwayIdpathway;
	private String modelEnzymeEcnumber;
	private int modelEnzymeModelProteinIdprotein;

	public ModelPathwayHasEnzymeId() {
	}

	public ModelPathwayHasEnzymeId(int pathwayIdpathway, String modelEnzymeEcnumber,
			int modelEnzymeModelProteinIdprotein) {
		this.pathwayIdpathway = pathwayIdpathway;
		this.modelEnzymeEcnumber = modelEnzymeEcnumber;
		this.modelEnzymeModelProteinIdprotein = modelEnzymeModelProteinIdprotein;
	}

	@Column(name = "pathway_idpathway", nullable = false)
	public int getPathwayIdpathway() {
		return this.pathwayIdpathway;
	}

	public void setPathwayIdpathway(int pathwayIdpathway) {
		this.pathwayIdpathway = pathwayIdpathway;
	}

	@Column(name = "model_enzyme_ecnumber", nullable = false, length = 15)
	public String getModelEnzymeEcnumber() {
		return this.modelEnzymeEcnumber;
	}

	public void setModelEnzymeEcnumber(String modelEnzymeEcnumber) {
		this.modelEnzymeEcnumber = modelEnzymeEcnumber;
	}

	@Column(name = "model_enzyme_model_protein_idprotein", nullable = false)
	public int getModelEnzymeModelProteinIdprotein() {
		return this.modelEnzymeModelProteinIdprotein;
	}

	public void setModelEnzymeModelProteinIdprotein(int modelEnzymeModelProteinIdprotein) {
		this.modelEnzymeModelProteinIdprotein = modelEnzymeModelProteinIdprotein;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelPathwayHasEnzymeId))
			return false;
		ModelPathwayHasEnzymeId castOther = (ModelPathwayHasEnzymeId) other;

		return (this.getPathwayIdpathway() == castOther.getPathwayIdpathway())
				&& ((this.getModelEnzymeEcnumber() == castOther.getModelEnzymeEcnumber())
						|| (this.getModelEnzymeEcnumber() != null && castOther.getModelEnzymeEcnumber() != null
								&& this.getModelEnzymeEcnumber().equals(castOther.getModelEnzymeEcnumber())))
				&& (this.getModelEnzymeModelProteinIdprotein() == castOther.getModelEnzymeModelProteinIdprotein());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPathwayIdpathway();
		result = 37 * result + (getModelEnzymeEcnumber() == null ? 0 : this.getModelEnzymeEcnumber().hashCode());
		result = 37 * result + this.getModelEnzymeModelProteinIdprotein();
		return result;
	}

}
