package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ModelMetabolicRegulation generated by hbm2java
 */
@Entity
@Table(name = "model_metabolic_regulation")
public class ModelMetabolicRegulation implements java.io.Serializable {

	private ModelMetabolicRegulationId id;
	private ModelCompound modelCompound;
	private ModelProtein modelProtein;
	private Character mode;
	private String mechanism;

	public ModelMetabolicRegulation() {
	}

	public ModelMetabolicRegulation(ModelMetabolicRegulationId id, ModelCompound modelCompound,
			ModelProtein modelProtein) {
		this.id = id;
		this.modelCompound = modelCompound;
		this.modelProtein = modelProtein;
	}

	public ModelMetabolicRegulation(ModelMetabolicRegulationId id, ModelCompound modelCompound,
			ModelProtein modelProtein, Character mode, String mechanism) {
		this.id = id;
		this.modelCompound = modelCompound;
		this.modelProtein = modelProtein;
		this.mode = mode;
		this.mechanism = mechanism;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "modelProteinIdprotein", column = @Column(name = "model_protein_idprotein", nullable = false)),
			@AttributeOverride(name = "modelCompoundIdcompound", column = @Column(name = "model_compound_idcompound", nullable = false)) })
	public ModelMetabolicRegulationId getId() {
		return this.id;
	}

	public void setId(ModelMetabolicRegulationId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_compound_idcompound", nullable = false, insertable = false, updatable = false)
	public ModelCompound getModelCompound() {
		return this.modelCompound;
	}

	public void setModelCompound(ModelCompound modelCompound) {
		this.modelCompound = modelCompound;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_protein_idprotein", nullable = false, insertable = false, updatable = false)
	public ModelProtein getModelProtein() {
		return this.modelProtein;
	}

	public void setModelProtein(ModelProtein modelProtein) {
		this.modelProtein = modelProtein;
	}

	@Column(name = "mode", length = 1)
	public Character getMode() {
		return this.mode;
	}

	public void setMode(Character mode) {
		this.mode = mode;
	}

	@Column(name = "mechanism", length = 25)
	public String getMechanism() {
		return this.mechanism;
	}

	public void setMechanism(String mechanism) {
		this.mechanism = mechanism;
	}

}
