package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ModelStoichiometry generated by hbm2java
 */
@Entity
@Table(name = "model_stoichiometry")
public class ModelStoichiometry implements java.io.Serializable {

	private int idstoichiometry;
	private ModelCompartment modelCompartment;
	private ModelCompound modelCompound;
	private ModelReaction modelReaction;
	private float stoichiometricCoefficient;

	public ModelStoichiometry() {
	}

	public ModelStoichiometry(int idstoichiometry, ModelCompartment modelCompartment, ModelCompound modelCompound,
			ModelReaction modelReaction, float stoichiometricCoefficient) {
		this.idstoichiometry = idstoichiometry;
		this.modelCompartment = modelCompartment;
		this.modelCompound = modelCompound;
		this.modelReaction = modelReaction;
		this.stoichiometricCoefficient = stoichiometricCoefficient;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "idstoichiometry", unique = true, nullable = false)
	public int getIdstoichiometry() {
		return this.idstoichiometry;
	}

	public void setIdstoichiometry(int idstoichiometry) {
		this.idstoichiometry = idstoichiometry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_compartment_idcompartment", nullable = false)
	public ModelCompartment getModelCompartment() {
		return this.modelCompartment;
	}

	public void setModelCompartment(ModelCompartment modelCompartment) {
		this.modelCompartment = modelCompartment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_compound_idcompound", nullable = false)
	public ModelCompound getModelCompound() {
		return this.modelCompound;
	}

	public void setModelCompound(ModelCompound modelCompound) {
		this.modelCompound = modelCompound;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_reaction_idreaction", nullable = false)
	public ModelReaction getModelReaction() {
		return this.modelReaction;
	}

	public void setModelReaction(ModelReaction modelReaction) {
		this.modelReaction = modelReaction;
	}

	@Column(name = "stoichiometric_coefficient", nullable = false, precision = 12, scale = 0)
	public float getStoichiometricCoefficient() {
		return this.stoichiometricCoefficient;
	}

	public void setStoichiometricCoefficient(float stoichiometricCoefficient) {
		this.stoichiometricCoefficient = stoichiometricCoefficient;
	}

}
