package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Sep 11, 2019 1:12:29 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ModelSubunit generated by hbm2java
 */
@Entity
@Table(name = "model_subunit")
public class ModelSubunit implements java.io.Serializable {

	private ModelSubunitId id;
	private ModelGene modelGene;
	private ModelProtein modelProtein;

	public ModelSubunit() {
	}

	public ModelSubunit(ModelSubunitId id, ModelGene modelGene, ModelProtein modelProtein) {
		this.id = id;
		this.modelGene = modelGene;
		this.modelProtein = modelProtein;
	}


	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "modelGeneIdgene", column = @Column(name = "model_gene_idgene", nullable = false)),
			@AttributeOverride(name = "modelProteinIdprotein", column = @Column(name = "model_protein_idprotein", nullable = false)) })
	public ModelSubunitId getId() {
		return this.id;
	}

	public void setId(ModelSubunitId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_gene_idgene", nullable = false, insertable = false, updatable = false)
	public ModelGene getModelGene() {
		return this.modelGene;
	}

	public void setModelGene(ModelGene modelGene) {
		this.modelGene = modelGene;
	}
	
	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_protein_idprotein", nullable = false, insertable = false, updatable = false)
	public ModelProtein getModelProtein() {
		return this.modelProtein;
	}

	public void setModelProtein(ModelProtein modelProtein) {
		this.modelProtein = modelProtein;
	}

}
