package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelModulesHasCompoundId generated by hbm2java
 */
@Embeddable
public class ModelModulesHasCompoundId implements java.io.Serializable {

	private int modelCompoundIdcompound;
	private int modelModuleId;

	public ModelModulesHasCompoundId() {
	}

	public ModelModulesHasCompoundId(int modelCompoundIdcompound, int modelModuleId) {
		this.modelCompoundIdcompound = modelCompoundIdcompound;
		this.modelModuleId = modelModuleId;
	}

	@Column(name = "model_compound_idcompound", nullable = false)
	public int getModelCompoundIdcompound() {
		return this.modelCompoundIdcompound;
	}

	public void setModelCompoundIdcompound(int modelCompoundIdcompound) {
		this.modelCompoundIdcompound = modelCompoundIdcompound;
	}

	@Column(name = "model_module_id", nullable = false)
	public int getModelModuleId() {
		return this.modelModuleId;
	}

	public void setModelModuleId(int modelModuleId) {
		this.modelModuleId = modelModuleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelModulesHasCompoundId))
			return false;
		ModelModulesHasCompoundId castOther = (ModelModulesHasCompoundId) other;

		return (this.getModelCompoundIdcompound() == castOther.getModelCompoundIdcompound())
				&& (this.getModelModuleId() == castOther.getModelModuleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelCompoundIdcompound();
		result = 37 * result + this.getModelModuleId();
		return result;
	}

}
