package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Oct 29, 2019 3:55:35 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelModuleHasModelProteinId generated by hbm2java
 */
@Embeddable
public class ModelModuleHasModelProteinId implements java.io.Serializable {

	private int modelModuleId;
	private int modelProteinIdprotein;

	public ModelModuleHasModelProteinId() {
	}

	public ModelModuleHasModelProteinId(int modelModuleId, int modelProteinIdprotein) {
		this.modelModuleId = modelModuleId;
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	@Column(name = "model_module_id", nullable = false)
	public int getModelModuleId() {
		return this.modelModuleId;
	}

	public void setModelModuleId(int modelModuleId) {
		this.modelModuleId = modelModuleId;
	}

	@Column(name = "model_protein_idprotein", nullable = false)
	public int getModelProteinIdprotein() {
		return this.modelProteinIdprotein;
	}

	public void setModelProteinIdprotein(int modelProteinIdprotein) {
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelModuleHasModelProteinId))
			return false;
		ModelModuleHasModelProteinId castOther = (ModelModuleHasModelProteinId) other;

		return (this.getModelModuleId() == castOther.getModelModuleId())
				&& (this.getModelProteinIdprotein() == castOther.getModelProteinIdprotein());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelModuleId();
		result = 37 * result + this.getModelProteinIdprotein();
		return result;
	}

}
