package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;


/**
 * ModelCompartment generated by hbm2java
 */
@Entity
@Table(name = "model_compartment", uniqueConstraints = {
		@UniqueConstraint(columnNames = "abbreviation"), @UniqueConstraint(columnNames = "name") })
public class ModelCompartment implements java.io.Serializable {

	private int idcompartment;
	private String name;
	private String abbreviation;
	private Set<ModelStoichiometry> modelStoichiometries = new HashSet<ModelStoichiometry>(0);
	private Set<ModelReaction> modelReactions = new HashSet<ModelReaction>(0);
	private Set<ModelGeneHasCompartment> modelGeneHasCompartments = new HashSet<ModelGeneHasCompartment>(0);

	public ModelCompartment() {
	}

	public ModelCompartment(int idcompartment) {
		this.idcompartment = idcompartment;
	}
	public ModelCompartment(int idcompartment, String name, String abbreviation,
			Set<ModelStoichiometry> modelStoichiometries, Set<ModelReaction> modelReactions,
			Set<ModelGeneHasCompartment> modelGeneHasCompartments) {
		this.idcompartment = idcompartment;
		this.name = name;
		this.abbreviation = abbreviation;
		this.modelStoichiometries = modelStoichiometries;
		this.modelReactions = modelReactions;
		this.modelGeneHasCompartments = modelGeneHasCompartments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "idcompartment", unique = true, nullable = false)
	public int getIdcompartment() {
		return this.idcompartment;
	}
	public void setIdcompartment(int idcompartment) {
		this.idcompartment = idcompartment;
	}

	@Column(name = "name", unique = true, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "abbreviation", unique = true, length = 20)
	public String getAbbreviation() {
		return this.abbreviation;
	}
	
	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

    @XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelCompartment")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelStoichiometry> getModelStoichiometries() {
		return this.modelStoichiometries;
	}

	public void setModelStoichiometries(Set<ModelStoichiometry> modelStoichiometries) {
		this.modelStoichiometries = modelStoichiometries;
	}

    @XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelCompartment")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelReaction> getModelReactions() {
		return this.modelReactions;
	}

	public void setModelReactions(Set<ModelReaction> modelReactions) {
		this.modelReactions = modelReactions;
	}

    @XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelCompartment")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelGeneHasCompartment> getModelGeneHasCompartments() {
		return this.modelGeneHasCompartments;
	}

	public void setModelGeneHasCompartments(Set<ModelGeneHasCompartment> modelGeneHasCompartments) {
		this.modelGeneHasCompartments = modelGeneHasCompartments;
	}

}
