package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ModelModuleHasOrthology generated by hbm2java
 */
@Entity
@Table(name = "model_module_has_orthology")
public class ModelModuleHasOrthology implements java.io.Serializable {

	private ModelModuleHasOrthologyId id;
	private ModelModule modelModule;
	private ModelOrthology modelOrthology;

	public ModelModuleHasOrthology() {
	}

	public ModelModuleHasOrthology(ModelModuleHasOrthologyId id, ModelModule modelModule,
			ModelOrthology modelOrthology) {
		this.id = id;
		this.modelModule = modelModule;
		this.modelOrthology = modelOrthology;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "modelModuleId", column = @Column(name = "model_module_id", nullable = false)),
			@AttributeOverride(name = "modelOrthologyId", column = @Column(name = "model_orthology_id", nullable = false)) })
	public ModelModuleHasOrthologyId getId() {
		return this.id;
	}

	public void setId(ModelModuleHasOrthologyId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_module_id", nullable = false, insertable = false, updatable = false)
	public ModelModule getModelModule() {
		return this.modelModule;
	}

	public void setModelModule(ModelModule modelModule) {
		this.modelModule = modelModule;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_orthology_id", nullable = false, insertable = false, updatable = false)
	public ModelOrthology getModelOrthology() {
		return this.modelOrthology;
	}

	public void setModelOrthology(ModelOrthology modelOrthology) {
		this.modelOrthology = modelOrthology;
	}

}
