package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 22, 2019 6:40:34 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ModelAliases generated by hbm2java
 */
@Entity
@Table(name = "model_aliases")
public class ModelAliases implements java.io.Serializable {

	private int idalias;
	private String class_;
	private int entity;
	private String alias;

	public ModelAliases() {
	}

	public ModelAliases(int idalias, String class_, int entity, String alias) {
		this.idalias = idalias;
		this.class_ = class_;
		this.entity = entity;
		this.alias = alias;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "idalias", unique = true, nullable = false)
	public int getIdalias() {
		return this.idalias;
	}

	public void setIdalias(int idalias) {
		this.idalias = idalias;
	}

	@Column(name = "class", nullable = false, length = 2)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "entity", nullable = false)
	public int getEntity() {
		return this.entity;
	}

	public void setEntity(int entity) {
		this.entity = entity;
	}

	@Column(name = "alias", nullable = false, length = 1200)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

}
