package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelDictionaryId generated by hbm2java
 */
@Embeddable
public class ModelDictionaryId implements java.io.Serializable {

	private String class_;
	private String aliases;

	public ModelDictionaryId() {
	}

	public ModelDictionaryId(String class_, String aliases) {
		this.class_ = class_;
		this.aliases = aliases;
	}

	@Column(name = "class", nullable = false, length = 1)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "aliases", nullable = false, length = 250)
	public String getAliases() {
		return this.aliases;
	}

	public void setAliases(String aliases) {
		this.aliases = aliases;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelDictionaryId))
			return false;
		ModelDictionaryId castOther = (ModelDictionaryId) other;

		return ((this.getClass_() == castOther.getClass_()) || (this.getClass_() != null
				&& castOther.getClass_() != null && this.getClass_().equals(castOther.getClass_())))
				&& ((this.getAliases() == castOther.getAliases()) || (this.getAliases() != null
						&& castOther.getAliases() != null && this.getAliases().equals(castOther.getAliases())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getClass_() == null ? 0 : this.getClass_().hashCode());
		result = 37 * result + (getAliases() == null ? 0 : this.getAliases().hashCode());
		return result;
	}

}
