package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * ModelFeature generated by hbm2java
 */
@Entity
@Table(name = "model_feature")
public class ModelFeature implements java.io.Serializable {

	private int idfeature;
	private String class_;
	private String description;
	private Integer startPosition;
	private Integer endPosition;
	private Set<ModelSequenceFeature> modelSequenceFeatures = new HashSet<ModelSequenceFeature>(0);

	public ModelFeature() {
	}

	public ModelFeature(int idfeature) {
		this.idfeature = idfeature;
	}

	public ModelFeature(int idfeature, String class_, String description, Integer startPosition, Integer endPosition,
			Set<ModelSequenceFeature> modelSequenceFeatures) {
		this.idfeature = idfeature;
		this.class_ = class_;
		this.description = description;
		this.startPosition = startPosition;
		this.endPosition = endPosition;
		this.modelSequenceFeatures = modelSequenceFeatures;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "idfeature", unique = true, nullable = false)
	public int getIdfeature() {
		return this.idfeature;
	}

	public void setIdfeature(int idfeature) {
		this.idfeature = idfeature;
	}

	@Column(name = "class", length = 50)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "description", length = 1300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "start_position")
	public Integer getStartPosition() {
		return this.startPosition;
	}

	public void setStartPosition(Integer startPosition) {
		this.startPosition = startPosition;
	}

	@Column(name = "end_position")
	public Integer getEndPosition() {
		return this.endPosition;
	}

	public void setEndPosition(Integer endPosition) {
		this.endPosition = endPosition;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelFeature")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelSequenceFeature> getModelSequenceFeatures() {
		return this.modelSequenceFeatures;
	}

	public void setModelSequenceFeatures(Set<ModelSequenceFeature> modelSequenceFeatures) {
		this.modelSequenceFeatures = modelSequenceFeatures;
	}

}
