package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ModelEntityisfrom generated by hbm2java
 */
@Entity
@Table(name = "model_entityisfrom")
public class ModelEntityisfrom implements java.io.Serializable {

	private int modelStrainIdstrain;
	private ModelStrain modelStrain;
	private Integer wid;

	public ModelEntityisfrom() {
	}

	public ModelEntityisfrom(ModelStrain modelStrain) {
		this.modelStrain = modelStrain;
	}

	public ModelEntityisfrom(ModelStrain modelStrain, Integer wid) {
		this.modelStrain = modelStrain;
		this.wid = wid;
	}

	@GenericGenerator(name = "pt.uminho.ceb.biosystems.merlin.entities.ModelEntityisfromIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "modelStrain"))
	@Id
	@GeneratedValue(generator = "pt.uminho.ceb.biosystems.merlin.entities.ModelEntityisfromIdGenerator")

	@Column(name = "model_strain_idstrain", unique = true, nullable = false)
	public int getModelStrainIdstrain() {
		return this.modelStrainIdstrain;
	}

	public void setModelStrainIdstrain(int modelStrainIdstrain) {
		this.modelStrainIdstrain = modelStrainIdstrain;
	}

	@XmlTransient
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ModelStrain getModelStrain() {
		return this.modelStrain;
	}

	public void setModelStrain(ModelStrain modelStrain) {
		this.modelStrain = modelStrain;
	}

	@Column(name = "wid")
	public Integer getWid() {
		return this.wid;
	}

	public void setWid(Integer wid) {
		this.wid = wid;
	}

}
