package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * ModelReaction generated by hbm2java
 */
@Entity
@Table(name = "model_reaction")
public class ModelReaction implements java.io.Serializable {

	private int idreaction;
	private ModelCompartment modelCompartment;
	private ModelReactionLabels modelReactionLabels;
	private String booleanRule;
	private Boolean inModel;
	private String notes;
	private Float lowerBound;
	private Float upperBound;
	private Set<ModelPathwayHasReaction> modelPathwayHasReactions = new HashSet<ModelPathwayHasReaction>(0);
	private Set<ModelStoichiometry> modelStoichiometries = new HashSet<ModelStoichiometry>(0);
	private Set<ModelReactionHasModelProtein> modelReactionHasModelProteins = new HashSet<ModelReactionHasModelProtein>(0);

	public ModelReaction() {
	}

	public ModelReaction(int idreaction, ModelReactionLabels modelReactionLabels) {
		this.idreaction = idreaction;
		this.modelReactionLabels = modelReactionLabels;
	}

	public ModelReaction(int idreaction, ModelCompartment modelCompartment, ModelReactionLabels modelReactionLabels,
			String booleanRule, Boolean inModel, String notes, Float lowerBound, Float upperBound,
			Set<ModelPathwayHasReaction> modelPathwayHasReactions,
			Set<ModelStoichiometry> modelStoichiometries,
			Set<ModelReactionHasModelProtein> modelReactionHasModelProteins) {
		this.idreaction = idreaction;
		this.modelCompartment = modelCompartment;
		this.modelReactionLabels = modelReactionLabels;
		this.booleanRule = booleanRule;
		this.inModel = inModel;
		this.notes = notes;
		this.lowerBound = lowerBound;
		this.upperBound = upperBound;
		this.modelPathwayHasReactions = modelPathwayHasReactions;
		this.modelStoichiometries = modelStoichiometries;
		this.modelReactionHasModelProteins = modelReactionHasModelProteins;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "idreaction", unique = true, nullable = false)
	public int getIdreaction() {
		return this.idreaction;
	}

	public void setIdreaction(int idreaction) {
		this.idreaction = idreaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "compartment_idcompartment")
	public ModelCompartment getModelCompartment() {
		return this.modelCompartment;
	}

	public void setModelCompartment(ModelCompartment modelCompartment) {
		this.modelCompartment = modelCompartment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_reaction_labels_idreaction_label", nullable = false)
	public ModelReactionLabels getModelReactionLabels() {
		return this.modelReactionLabels;
	}

	public void setModelReactionLabels(ModelReactionLabels modelReactionLabels) {
		this.modelReactionLabels = modelReactionLabels;
	}

	@Column(name = "boolean_rule", length = 65535, columnDefinition="Text")
	public String getBooleanRule() {
		return this.booleanRule;
	}

	public void setBooleanRule(String booleanRule) {
		this.booleanRule = booleanRule;
	}

	@Column(name = "inModel")
	public Boolean getInModel() {
		return this.inModel;
	}

	public void setInModel(Boolean inModel) {
		this.inModel = inModel;
	}

	@Column(name = "notes", length = 65535, columnDefinition="Text")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "lowerBound", precision = 12, scale = 0)
	public Float getLowerBound() {
		return this.lowerBound;
	}

	public void setLowerBound(Float lowerBound) {
		this.lowerBound = lowerBound;
	}

	@Column(name = "upperBound", precision = 12, scale = 0)
	public Float getUpperBound() {
		return this.upperBound;
	}

	public void setUpperBound(Float upperBound) {
		this.upperBound = upperBound;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelReaction")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelPathwayHasReaction> getModelPathwayHasReactions() {
		return this.modelPathwayHasReactions;
	}

	public void setModelPathwayHasReactions(Set<ModelPathwayHasReaction> modelPathwayHasReactions) {
		this.modelPathwayHasReactions = modelPathwayHasReactions;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelReaction")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelStoichiometry> getModelStoichiometries() {
		return this.modelStoichiometries;
	}

	public void setModelStoichiometries(Set<ModelStoichiometry> modelStoichiometries) {
		this.modelStoichiometries = modelStoichiometries;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelReaction")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelReactionHasModelProtein> getModelReactionHasModelProteins() {
		return this.modelReactionHasModelProteins;
	}

	
	public void setModelReactionHasModelProteins(Set<ModelReactionHasModelProtein> modelReactionHasModelProteins) {
		this.modelReactionHasModelProteins = modelReactionHasModelProteins;
	}

}
