package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Sep 11, 2019 1:12:29 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelSubunitId generated by hbm2java
 */
@Embeddable
public class ModelSubunitId implements java.io.Serializable {

	private int modelGeneIdgene;
	private int modelProteinIdprotein;

	public ModelSubunitId() {
	}

	public ModelSubunitId(int modelGeneIdgene, int modelProteinIdprotein) {
		this.modelGeneIdgene = modelGeneIdgene;
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	@Column(name = "model_gene_idgene", nullable = false)
	public int getModelGeneIdgene() {
		return this.modelGeneIdgene;
	}

	public void setModelGeneIdgene(int modelGeneIdgene) {
		this.modelGeneIdgene = modelGeneIdgene;
	}

	@Column(name = "model_protein_idprotein", nullable = false)
	public int getModelProteinIdprotein() {
		return this.modelProteinIdprotein;
	}

	public void setModelProteinIdprotein(int modelProteinIdprotein) {
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelSubunitId))
			return false;
		ModelSubunitId castOther = (ModelSubunitId) other;

		return (this.getModelGeneIdgene() == castOther.getModelGeneIdgene())
				&& (this.getModelProteinIdprotein() == castOther.getModelProteinIdprotein());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelGeneIdgene();
		result = 37 * result + this.getModelProteinIdprotein();
		return result;
	}

}
