package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ModelPathwayHasReaction generated by hbm2java
 */
@Entity
@Table(name = "model_pathway_has_reaction")
public class ModelPathwayHasReaction implements java.io.Serializable {

	private ModelPathwayHasReactionId id;
	private ModelPathway modelPathway;
	private ModelReaction modelReaction;

	public ModelPathwayHasReaction() {
	}

	public ModelPathwayHasReaction(ModelPathwayHasReactionId id, ModelPathway modelPathway,
			ModelReaction modelReaction) {
		this.id = id;
		this.modelPathway = modelPathway;
		this.modelReaction = modelReaction;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pathwayIdpathway", column = @Column(name = "pathway_idpathway", nullable = false)),
			@AttributeOverride(name = "reactionIdreaction", column = @Column(name = "reaction_idreaction", nullable = false)) })
	public ModelPathwayHasReactionId getId() {
		return this.id;
	}

	public void setId(ModelPathwayHasReactionId id) {
		this.id = id;
	}
	
	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pathway_idpathway", nullable = false, insertable = false, updatable = false)
	public ModelPathway getModelPathway() {
		return this.modelPathway;
	}

	public void setModelPathway(ModelPathway modelPathway) {
		this.modelPathway = modelPathway;
	}
	
	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reaction_idreaction", nullable = false, insertable = false, updatable = false)
	public ModelReaction getModelReaction() {
		return this.modelReaction;
	}

	public void setModelReaction(ModelReaction modelReaction) {
		this.modelReaction = modelReaction;
	}

}
