package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ModelPathwayHasModule generated by hbm2java
 */
@Entity
@Table(name = "model_pathway_has_module")
public class ModelPathwayHasModule implements java.io.Serializable {

	private ModelPathwayHasModuleId id;
	private ModelModule modelModule;
	private ModelPathway modelPathway;

	public ModelPathwayHasModule() {
	}

	public ModelPathwayHasModule(ModelPathwayHasModuleId id, ModelModule modelModule, ModelPathway modelPathway) {
		this.id = id;
		this.modelModule = modelModule;
		this.modelPathway = modelPathway;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "modelPathwayIdpathway", column = @Column(name = "model_pathway_idpathway", nullable = false)),
			@AttributeOverride(name = "modelModuleId", column = @Column(name = "model_module_id", nullable = false)) })
	public ModelPathwayHasModuleId getId() {
		return this.id;
	}

	public void setId(ModelPathwayHasModuleId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_module_id", nullable = false, insertable = false, updatable = false)
	public ModelModule getModelModule() {
		return this.modelModule;
	}

	public void setModelModule(ModelModule modelModule) {
		this.modelModule = modelModule;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_pathway_idpathway", nullable = false, insertable = false, updatable = false)
	public ModelPathway getModelPathway() {
		return this.modelPathway;
	}

	public void setModelPathway(ModelPathway modelPathway) {
		this.modelPathway = modelPathway;
	}

}
