package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelGeneHasCompartmentId generated by hbm2java
 */
@Embeddable
public class ModelGeneHasCompartmentId implements java.io.Serializable {

	private int modelCompartmentIdcompartment;
	private int modelGeneIdgene;

	public ModelGeneHasCompartmentId() {
	}

	public ModelGeneHasCompartmentId(int modelCompartmentIdcompartment, int modelGeneIdgene) {
		this.modelCompartmentIdcompartment = modelCompartmentIdcompartment;
		this.modelGeneIdgene = modelGeneIdgene;
	}

	@Column(name = "model_compartment_idcompartment", nullable = false)
	public int getModelCompartmentIdcompartment() {
		return this.modelCompartmentIdcompartment;
	}

	public void setModelCompartmentIdcompartment(int modelCompartmentIdcompartment) {
		this.modelCompartmentIdcompartment = modelCompartmentIdcompartment;
	}

	@Column(name = "model_gene_idgene", nullable = false)
	public int getModelGeneIdgene() {
		return this.modelGeneIdgene;
	}

	public void setModelGeneIdgene(int modelGeneIdgene) {
		this.modelGeneIdgene = modelGeneIdgene;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelGeneHasCompartmentId))
			return false;
		ModelGeneHasCompartmentId castOther = (ModelGeneHasCompartmentId) other;

		return (this.getModelCompartmentIdcompartment() == castOther.getModelCompartmentIdcompartment())
				&& (this.getModelGeneIdgene() == castOther.getModelGeneIdgene());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelCompartmentIdcompartment();
		result = 37 * result + this.getModelGeneIdgene();
		return result;
	}

}
