package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelGeneHasOrthologyId generated by hbm2java
 */
@Embeddable
public class ModelGeneHasOrthologyId implements java.io.Serializable {

	private int modelOrthologyId;
	private int modelGeneIdgene;

	public ModelGeneHasOrthologyId() {
	}

	public ModelGeneHasOrthologyId(int modelOrthologyId, int modelGeneIdgene) {
		this.modelOrthologyId = modelOrthologyId;
		this.modelGeneIdgene = modelGeneIdgene;
	}

	@Column(name = "model_orthology_id", nullable = false)
	public int getModelOrthologyId() {
		return this.modelOrthologyId;
	}

	public void setModelOrthologyId(int modelOrthologyId) {
		this.modelOrthologyId = modelOrthologyId;
	}

	@Column(name = "model_gene_idgene", nullable = false)
	public int getModelGeneIdgene() {
		return this.modelGeneIdgene;
	}

	public void setModelGeneIdgene(int modelGeneIdgene) {
		this.modelGeneIdgene = modelGeneIdgene;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelGeneHasOrthologyId))
			return false;
		ModelGeneHasOrthologyId castOther = (ModelGeneHasOrthologyId) other;

		return (this.getModelOrthologyId() == castOther.getModelOrthologyId())
				&& (this.getModelGeneIdgene() == castOther.getModelGeneIdgene());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelOrthologyId();
		result = 37 * result + this.getModelGeneIdgene();
		return result;
	}

}
