package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelDblinks generated by hbm2java
 */
@Entity
@Table(name = "model_dblinks")
public class ModelDblinks implements java.io.Serializable {

	private ModelDblinksId id;
	private String externalId;

	public ModelDblinks() {
	}

	public ModelDblinks(ModelDblinksId id, String externalId) {
		this.id = id;
		this.externalId = externalId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "class_", column = @Column(name = "class", nullable = false, length = 2)),
			@AttributeOverride(name = "internalId", column = @Column(name = "internal_id", nullable = false)),
			@AttributeOverride(name = "externalDatabase", column = @Column(name = "external_database", nullable = false, length = 150)) })
	public ModelDblinksId getId() {
		return this.id;
	}

	public void setId(ModelDblinksId id) {
		this.id = id;
	}

	@Column(name = "external_id", nullable = false, length = 65535, columnDefinition="Text")
	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

}
