package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelProteinCompositionId generated by hbm2java
 */
@Embeddable
public class ModelProteinCompositionId implements java.io.Serializable {

	private int subunit;
	private int modelProteinIdprotein;

	public ModelProteinCompositionId() {
	}

	public ModelProteinCompositionId(int subunit, int modelProteinIdprotein) {
		this.subunit = subunit;
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	@Column(name = "subunit", nullable = false)
	public int getSubunit() {
		return this.subunit;
	}

	public void setSubunit(int subunit) {
		this.subunit = subunit;
	}

	@Column(name = "model_protein_idprotein", nullable = false)
	public int getModelProteinIdprotein() {
		return this.modelProteinIdprotein;
	}

	public void setModelProteinIdprotein(int modelProteinIdprotein) {
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelProteinCompositionId))
			return false;
		ModelProteinCompositionId castOther = (ModelProteinCompositionId) other;

		return (this.getSubunit() == castOther.getSubunit())
				&& (this.getModelProteinIdprotein() == castOther.getModelProteinIdprotein());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSubunit();
		result = 37 * result + this.getModelProteinIdprotein();
		return result;
	}

}
