package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ModelModulesHasCompound generated by hbm2java
 */
@Entity
@Table(name = "model_modules_has_compound")
public class ModelModulesHasCompound implements java.io.Serializable {

	private ModelModulesHasCompoundId id;
	private ModelCompound modelCompound;
	private ModelModule modelModule;

	public ModelModulesHasCompound() {
	}

	public ModelModulesHasCompound(ModelModulesHasCompoundId id, ModelCompound modelCompound, ModelModule modelModule) {
		this.id = id;
		this.modelCompound = modelCompound;
		this.modelModule = modelModule;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "modelCompoundIdcompound", column = @Column(name = "model_compound_idcompound", nullable = false)),
			@AttributeOverride(name = "modelModuleId", column = @Column(name = "model_module_id", nullable = false)) })
	public ModelModulesHasCompoundId getId() {
		return this.id;
	}

	public void setId(ModelModulesHasCompoundId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_compound_idcompound", nullable = false, insertable = false, updatable = false)
	public ModelCompound getModelCompound() {
		return this.modelCompound;
	}

	public void setModelCompound(ModelCompound modelCompound) {
		this.modelCompound = modelCompound;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_module_id", nullable = false, insertable = false, updatable = false)
	public ModelModule getModelModule() {
		return this.modelModule;
	}

	public void setModelModule(ModelModule modelModule) {
		this.modelModule = modelModule;
	}

}
