package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ModelSameAs generated by hbm2java
 */
@Entity
@Table(name = "model_same_as")
public class ModelSameAs implements java.io.Serializable {

	private ModelSameAsId id;
	private ModelCompound modelCompoundBySimilarMetaboliteid;
	private ModelCompound modelCompoundByMetaboliteid;

	public ModelSameAs() {
	}

	public ModelSameAs(ModelSameAsId id, ModelCompound modelCompoundBySimilarMetaboliteid,
			ModelCompound modelCompoundByMetaboliteid) {
		this.id = id;
		this.modelCompoundBySimilarMetaboliteid = modelCompoundBySimilarMetaboliteid;
		this.modelCompoundByMetaboliteid = modelCompoundByMetaboliteid;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "metaboliteid", column = @Column(name = "metaboliteid", nullable = false)),
			@AttributeOverride(name = "similarMetaboliteid", column = @Column(name = "similar_metaboliteid", nullable = false)) })
	public ModelSameAsId getId() {
		return this.id;
	}

	public void setId(ModelSameAsId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "similar_metaboliteid", nullable = false, insertable = false, updatable = false)
	public ModelCompound getModelCompoundBySimilarMetaboliteid() {
		return this.modelCompoundBySimilarMetaboliteid;
	}

	public void setModelCompoundBySimilarMetaboliteid(ModelCompound modelCompoundBySimilarMetaboliteid) {
		this.modelCompoundBySimilarMetaboliteid = modelCompoundBySimilarMetaboliteid;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "metaboliteid", nullable = false, insertable = false, updatable = false)
	public ModelCompound getModelCompoundByMetaboliteid() {
		return this.modelCompoundByMetaboliteid;
	}

	public void setModelCompoundByMetaboliteid(ModelCompound modelCompoundByMetaboliteid) {
		this.modelCompoundByMetaboliteid = modelCompoundByMetaboliteid;
	}

}
