package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModelReactionHasEnzymeId generated by hbm2java
 */
@Embeddable
public class ModelReactionHasEnzymeId implements java.io.Serializable {

	private String modelEnzymeEcnumber;
	private int modelEnzymeModelProteinIdprotein;
	private int modelReactionIdreaction;

	public ModelReactionHasEnzymeId() {
	}

	public ModelReactionHasEnzymeId(String modelEnzymeEcnumber, int modelEnzymeModelProteinIdprotein,
			int modelReactionIdreaction) {
		this.modelEnzymeEcnumber = modelEnzymeEcnumber;
		this.modelEnzymeModelProteinIdprotein = modelEnzymeModelProteinIdprotein;
		this.modelReactionIdreaction = modelReactionIdreaction;
	}

	@Column(name = "model_enzyme_ecnumber", nullable = false, length = 15)
	public String getModelEnzymeEcnumber() {
		return this.modelEnzymeEcnumber;
	}

	public void setModelEnzymeEcnumber(String modelEnzymeEcnumber) {
		this.modelEnzymeEcnumber = modelEnzymeEcnumber;
	}

	@Column(name = "model_enzyme_model_protein_idprotein", nullable = false)
	public int getModelEnzymeModelProteinIdprotein() {
		return this.modelEnzymeModelProteinIdprotein;
	}

	public void setModelEnzymeModelProteinIdprotein(int modelEnzymeModelProteinIdprotein) {
		this.modelEnzymeModelProteinIdprotein = modelEnzymeModelProteinIdprotein;
	}

	@Column(name = "model_reaction_idreaction", nullable = false)
	public int getModelReactionIdreaction() {
		return this.modelReactionIdreaction;
	}

	public void setModelReactionIdreaction(int modelReactionIdreaction) {
		this.modelReactionIdreaction = modelReactionIdreaction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelReactionHasEnzymeId))
			return false;
		ModelReactionHasEnzymeId castOther = (ModelReactionHasEnzymeId) other;

		return ((this.getModelEnzymeEcnumber() == castOther.getModelEnzymeEcnumber())
				|| (this.getModelEnzymeEcnumber() != null && castOther.getModelEnzymeEcnumber() != null
						&& this.getModelEnzymeEcnumber().equals(castOther.getModelEnzymeEcnumber())))
				&& (this.getModelEnzymeModelProteinIdprotein() == castOther.getModelEnzymeModelProteinIdprotein())
				&& (this.getModelReactionIdreaction() == castOther.getModelReactionIdreaction());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getModelEnzymeEcnumber() == null ? 0 : this.getModelEnzymeEcnumber().hashCode());
		result = 37 * result + this.getModelEnzymeModelProteinIdprotein();
		result = 37 * result + this.getModelReactionIdreaction();
		return result;
	}

}
