package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * ModelReactionLabels generated by hbm2java
 */
@Entity
@Table(name = "model_reaction_labels", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class ModelReactionLabels implements java.io.Serializable {

	private int idreactionLabel;
	private String name;
	private String equation;
	private Boolean isGeneric;
	private Boolean isSpontaneous;
	private Boolean isNonEnzymatic;
	private String source;
	private Set<ModelReaction> modelReactions = new HashSet<ModelReaction>(0);

	public ModelReactionLabels() {
	}

	public ModelReactionLabels(int idreactionLabel, String name, String equation, String source) {
		this.idreactionLabel = idreactionLabel;
		this.name = name;
		this.equation = equation;
		this.source = source;
	}

	public ModelReactionLabels(int idreactionLabel, String name, String equation, Boolean isGeneric,
			Boolean isSpontaneous, Boolean isNonEnzymatic, String source, Set<ModelReaction> modelReactions) {
		this.idreactionLabel = idreactionLabel;
		this.name = name;
		this.equation = equation;
		this.isGeneric = isGeneric;
		this.isSpontaneous = isSpontaneous;
		this.isNonEnzymatic = isNonEnzymatic;
		this.source = source;
		this.modelReactions = modelReactions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "idreaction_label", unique = true, nullable = false)
	public int getIdreactionLabel() {
		return this.idreactionLabel;
	}

	public void setIdreactionLabel(int idreactionLabel) {
		this.idreactionLabel = idreactionLabel;
	}

	@Column(name = "name", unique = true, nullable = false, length = 400)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "equation", nullable = false, length = 65535, columnDefinition="Text")
	public String getEquation() {
		return this.equation;
	}

	public void setEquation(String equation) {
		this.equation = equation;
	}

	@Column(name = "isGeneric")
	public Boolean getIsGeneric() {
		return this.isGeneric;
	}

	public void setIsGeneric(Boolean isGeneric) {
		this.isGeneric = isGeneric;
	}

	@Column(name = "isSpontaneous")
	public Boolean getIsSpontaneous() {
		return this.isSpontaneous;
	}

	public void setIsSpontaneous(Boolean isSpontaneous) {
		this.isSpontaneous = isSpontaneous;
	}

	@Column(name = "isNonEnzymatic")
	public Boolean getIsNonEnzymatic() {
		return this.isNonEnzymatic;
	}

	public void setIsNonEnzymatic(Boolean isNonEnzymatic) {
		this.isNonEnzymatic = isNonEnzymatic;
	}

	@Column(name = "source", nullable = false, length = 45)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelReactionLabels")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<ModelReaction> getModelReactions() {
		return this.modelReactions;
	}

	public void setModelReactions(Set<ModelReaction> modelReactions) {
		this.modelReactions = modelReactions;
	}

}
