package pt.uminho.ceb.biosystems.merlin.entities.model;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModelDictionary generated by hbm2java
 */
@Entity
@Table(name = "model_dictionary")
public class ModelDictionary implements java.io.Serializable {

	private ModelDictionaryId id;
	private String commonName;

	public ModelDictionary() {
	}

	public ModelDictionary(ModelDictionaryId id) {
		this.id = id;
	}

	public ModelDictionary(ModelDictionaryId id, String commonName) {
		this.id = id;
		this.commonName = commonName;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "class_", column = @Column(name = "class", nullable = false, length = 1)),
			@AttributeOverride(name = "aliases", column = @Column(name = "aliases", nullable = false, length = 250)) })
	public ModelDictionaryId getId() {
		return this.id;
	}

	public void setId(ModelDictionaryId id) {
		this.id = id;
	}

	@Column(name = "common_name", length = 250)
	public String getCommonName() {
		return this.commonName;
	}

	public void setCommonName(String commonName) {
		this.commonName = commonName;
	}

}
