package pt.uminho.ceb.biosystems.merlin.entities.annotation.compartments;
// Generated Oct 16, 2019 3:46:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompartmentsAnnotationReportsHasCompartmentsId generated by hbm2java
 */
@Embeddable
public class CompartmentsAnnotationReportsHasCompartmentsId implements java.io.Serializable {

	private int modelGeneIdgene;
	private int compartmentsAnnotationCompartmentsId;

	public CompartmentsAnnotationReportsHasCompartmentsId() {
	}

	public CompartmentsAnnotationReportsHasCompartmentsId(int modelGeneIdgene,
			int compartmentsAnnotationCompartmentsId) {
		this.modelGeneIdgene = modelGeneIdgene;
		this.compartmentsAnnotationCompartmentsId = compartmentsAnnotationCompartmentsId;
	}

	@Column(name = "model_gene_idgene", nullable = false)
	public int getModelGeneIdgene() {
		return this.modelGeneIdgene;
	}

	public void setModelGeneIdgene(int modelGeneIdgene) {
		this.modelGeneIdgene = modelGeneIdgene;
	}

	@Column(name = "compartments_annotation_compartments_id", nullable = false)
	public int getCompartmentsAnnotationCompartmentsId() {
		return this.compartmentsAnnotationCompartmentsId;
	}

	public void setCompartmentsAnnotationCompartmentsId(int compartmentsAnnotationCompartmentsId) {
		this.compartmentsAnnotationCompartmentsId = compartmentsAnnotationCompartmentsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CompartmentsAnnotationReportsHasCompartmentsId))
			return false;
		CompartmentsAnnotationReportsHasCompartmentsId castOther = (CompartmentsAnnotationReportsHasCompartmentsId) other;

		return (this.getModelGeneIdgene() == castOther.getModelGeneIdgene()) && (this
				.getCompartmentsAnnotationCompartmentsId() == castOther.getCompartmentsAnnotationCompartmentsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModelGeneIdgene();
		result = 37 * result + this.getCompartmentsAnnotationCompartmentsId();
		return result;
	}

}
