package pt.uminho.ceb.biosystems.merlin.entities.annotation.compartments;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * CompartmentsAnnotationCompartments generated by hbm2java
 */
@Entity
@Table(name = "compartments_annotation_compartments")
public class CompartmentsAnnotationCompartments implements java.io.Serializable {

	private int id;
	private String name;
	private String abbreviation;
	private Set<CompartmentsAnnotationReportsHasCompartments> compartmentsAnnotationReportsHasCompartmentses = new HashSet<CompartmentsAnnotationReportsHasCompartments>(
			0);

	public CompartmentsAnnotationCompartments() {
	}

	public CompartmentsAnnotationCompartments(int id) {
		this.id = id;
	}

	public CompartmentsAnnotationCompartments(int id, String name, String abbreviation,
			Set<CompartmentsAnnotationReportsHasCompartments> compartmentsAnnotationReportsHasCompartmentses) {
		this.id = id;
		this.name = name;
		this.abbreviation = abbreviation;
		this.compartmentsAnnotationReportsHasCompartmentses = compartmentsAnnotationReportsHasCompartmentses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "abbreviation", length = 10)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compartmentsAnnotationCompartments")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<CompartmentsAnnotationReportsHasCompartments> getCompartmentsAnnotationReportsHasCompartmentses() {
		return this.compartmentsAnnotationReportsHasCompartmentses;
	}

	public void setCompartmentsAnnotationReportsHasCompartmentses(
			Set<CompartmentsAnnotationReportsHasCompartments> compartmentsAnnotationReportsHasCompartmentses) {
		this.compartmentsAnnotationReportsHasCompartmentses = compartmentsAnnotationReportsHasCompartmentses;
	}

}
