package pt.uminho.ceb.biosystems.merlin.entities.project;
// Generated Oct 16, 2019 11:41:19 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "projects")
public class Projects implements java.io.Serializable {

	private int id;
	private Integer organismId;
	private Boolean latestVersion;
	private Date date;
	private Integer projectVersion;
	private String organismName;
	private String organismLineage;
	private String compartmentsTool;
	private String referenceId;
	private String uid;
	private String assemblyRecord;
	private String assemblyAccession;
	private String accessionGenbank;
	private String accessionRefseq;
	private String submitter;
	private String genbankStatus;
	private String refseqStatus;
	private String assemblyLevel;
	private String lastUpdated;

	public Projects() {
	}

	public Projects(int id) {
		this.id = id;
	}

	public Projects(int id, Integer organismId, Boolean latestVersion, Date date, Integer projectVersion,
			String organismName, String organismLineage, String compartmentsTool, String referenceId, String uid,
			String assemblyRecord, String assemblyAccession, String accessionGenbank, String accessionRefseq,
			String submitter, String genbankStatus, String refseqStatus, String assemblyLevel, String lastUpdated) {
		this.id = id;
		this.organismId = organismId;
		this.latestVersion = latestVersion;
		this.date = date;
		this.projectVersion = projectVersion;
		this.organismName = organismName;
		this.organismLineage = organismLineage;
		this.compartmentsTool = compartmentsTool;
		this.referenceId = referenceId;
		this.uid = uid;
		this.assemblyRecord = assemblyRecord;
		this.assemblyAccession = assemblyAccession;
		this.accessionGenbank = accessionGenbank;
		this.accessionRefseq = accessionRefseq;
		this.submitter = submitter;
		this.genbankStatus = genbankStatus;
		this.refseqStatus = refseqStatus;
		this.assemblyLevel = assemblyLevel;
		this.lastUpdated = lastUpdated;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "organism_id")
	public Integer getOrganismId() {
		return this.organismId;
	}

	public void setOrganismId(Integer organismId) {
		this.organismId = organismId;
	}

	@Column(name = "latest_version")
	public Boolean getLatestVersion() {
		return this.latestVersion;
	}

	public void setLatestVersion(Boolean latestVersion) {
		this.latestVersion = latestVersion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "project_version")
	public Integer getProjectVersion() {
		return this.projectVersion;
	}

	public void setProjectVersion(Integer projectVersion) {
		this.projectVersion = projectVersion;
	}

	@Column(name = "organism_name", length = 1000)
	public String getOrganismName() {
		return this.organismName;
	}

	public void setOrganismName(String organismName) {
		this.organismName = organismName;
	}

	@Column(name = "organism_lineage", length = 3000)
	public String getOrganismLineage() {
		return this.organismLineage;
	}

	public void setOrganismLineage(String organismLineage) {
		this.organismLineage = organismLineage;
	}

	@Column(name = "compartments_tool", length = 90)
	public String getCompartmentsTool() {
		return this.compartmentsTool;
	}

	public void setCompartmentsTool(String compartmentsTool) {
		this.compartmentsTool = compartmentsTool;
	}

	@Column(name = "reference_id", length = 400)
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "uid", length = 400)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "assembly_record", length = 45)
	public String getAssemblyRecord() {
		return this.assemblyRecord;
	}

	public void setAssemblyRecord(String assemblyRecord) {
		this.assemblyRecord = assemblyRecord;
	}

	@Column(name = "assembly_accession", length = 45)
	public String getAssemblyAccession() {
		return this.assemblyAccession;
	}

	public void setAssemblyAccession(String assemblyAccession) {
		this.assemblyAccession = assemblyAccession;
	}

	@Column(name = "accession_genbank", length = 45)
	public String getAccessionGenbank() {
		return this.accessionGenbank;
	}

	public void setAccessionGenbank(String accessionGenbank) {
		this.accessionGenbank = accessionGenbank;
	}

	@Column(name = "accession_refseq", length = 45)
	public String getAccessionRefseq() {
		return this.accessionRefseq;
	}

	public void setAccessionRefseq(String accessionRefseq) {
		this.accessionRefseq = accessionRefseq;
	}

	@Column(name = "submitter", length = 45)
	public String getSubmitter() {
		return this.submitter;
	}

	public void setSubmitter(String submitter) {
		this.submitter = submitter;
	}

	@Column(name = "genbank_status", length = 45)
	public String getGenbankStatus() {
		return this.genbankStatus;
	}

	public void setGenbankStatus(String genbankStatus) {
		this.genbankStatus = genbankStatus;
	}

	@Column(name = "refseq_status", length = 45)
	public String getRefseqStatus() {
		return this.refseqStatus;
	}

	public void setRefseqStatus(String refseqStatus) {
		this.refseqStatus = refseqStatus;
	}

	@Column(name = "assembly_level", length = 45)
	public String getAssemblyLevel() {
		return this.assemblyLevel;
	}

	public void setAssemblyLevel(String assemblyLevel) {
		this.assemblyLevel = assemblyLevel;
	}
	
	@Column(name = "last_updated", length = 45)
	public String getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(String lastUpdated) {
		this.lastUpdated = lastUpdated;
	}


}
