package pt.uminho.ceb.biosystems.merlin.entities.regulatory;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import pt.uminho.ceb.biosystems.merlin.entities.model.ModelProtein;

/**
 * RegulatorySigmaPromoter generated by hbm2java
 */
@Entity
@Table(name = "regulatory_sigma_promoter")
public class RegulatorySigmaPromoter implements java.io.Serializable {

	private RegulatorySigmaPromoterId id;
	private ModelProtein modelProtein;
	private RegulatoryPromoter regulatoryPromoter;

	public RegulatorySigmaPromoter() {
	}

	public RegulatorySigmaPromoter(RegulatorySigmaPromoterId id, ModelProtein modelProtein,
			RegulatoryPromoter regulatoryPromoter) {
		this.id = id;
		this.modelProtein = modelProtein;
		this.regulatoryPromoter = regulatoryPromoter;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "modelProteinIdprotein", column = @Column(name = "model_protein_idprotein", nullable = false)),
			@AttributeOverride(name = "regulatoryPromoterIdpromoter", column = @Column(name = "regulatory_promoter_idpromoter", nullable = false)) })
	public RegulatorySigmaPromoterId getId() {
		return this.id;
	}

	public void setId(RegulatorySigmaPromoterId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_protein_idprotein", nullable = false, insertable = false, updatable = false)
	public ModelProtein getModelProtein() {
		return this.modelProtein;
	}

	public void setModelProtein(ModelProtein modelProtein) {
		this.modelProtein = modelProtein;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regulatory_promoter_idpromoter", nullable = false, insertable = false, updatable = false)
	public RegulatoryPromoter getRegulatoryPromoter() {
		return this.regulatoryPromoter;
	}

	public void setRegulatoryPromoter(RegulatoryPromoter regulatoryPromoter) {
		this.regulatoryPromoter = regulatoryPromoter;
	}

}
