package pt.uminho.ceb.biosystems.merlin.entities.regulatory;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * RegulatoryTranscriptionUnitPromoter generated by hbm2java
 */
@Entity
@Table(name = "regulatory_transcription_unit_promoter")
public class RegulatoryTranscriptionUnitPromoter implements java.io.Serializable {

	private RegulatoryTranscriptionUnitPromoterId id;
	private RegulatoryPromoter regulatoryPromoter;
	private RegulatoryTranscriptionUnit regulatoryTranscriptionUnit;

	public RegulatoryTranscriptionUnitPromoter() {
	}

	public RegulatoryTranscriptionUnitPromoter(RegulatoryTranscriptionUnitPromoterId id,
			RegulatoryPromoter regulatoryPromoter, RegulatoryTranscriptionUnit regulatoryTranscriptionUnit) {
		this.id = id;
		this.regulatoryPromoter = regulatoryPromoter;
		this.regulatoryTranscriptionUnit = regulatoryTranscriptionUnit;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "regulatoryTranscriptionUnitIdtranscriptionUnit", column = @Column(name = "regulatory_transcription_unit_idtranscription_unit", nullable = false)),
			@AttributeOverride(name = "regulatoryPromoterIdpromoter", column = @Column(name = "regulatory_promoter_idpromoter", nullable = false)) })
	public RegulatoryTranscriptionUnitPromoterId getId() {
		return this.id;
	}

	public void setId(RegulatoryTranscriptionUnitPromoterId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regulatory_promoter_idpromoter", nullable = false, insertable = false, updatable = false)
	public RegulatoryPromoter getRegulatoryPromoter() {
		return this.regulatoryPromoter;
	}

	public void setRegulatoryPromoter(RegulatoryPromoter regulatoryPromoter) {
		this.regulatoryPromoter = regulatoryPromoter;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regulatory_transcription_unit_idtranscription_unit", nullable = false, insertable = false, updatable = false)
	public RegulatoryTranscriptionUnit getRegulatoryTranscriptionUnit() {
		return this.regulatoryTranscriptionUnit;
	}

	public void setRegulatoryTranscriptionUnit(RegulatoryTranscriptionUnit regulatoryTranscriptionUnit) {
		this.regulatoryTranscriptionUnit = regulatoryTranscriptionUnit;
	}

}
