package pt.uminho.ceb.biosystems.merlin.entities.regulatory;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegulatoryEventId generated by hbm2java
 */
@Embeddable
public class RegulatoryEventId implements java.io.Serializable {

	private int regulatoryRiFunctionIdriFunction;
	private int regulatoryPromoterIdpromoter;
	private int modelProteinIdprotein;

	public RegulatoryEventId() {
	}

	public RegulatoryEventId(int regulatoryRiFunctionIdriFunction, int regulatoryPromoterIdpromoter,
			int modelProteinIdprotein) {
		this.regulatoryRiFunctionIdriFunction = regulatoryRiFunctionIdriFunction;
		this.regulatoryPromoterIdpromoter = regulatoryPromoterIdpromoter;
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	@Column(name = "regulatory_ri_function_idri_function", nullable = false)
	public int getRegulatoryRiFunctionIdriFunction() {
		return this.regulatoryRiFunctionIdriFunction;
	}

	public void setRegulatoryRiFunctionIdriFunction(int regulatoryRiFunctionIdriFunction) {
		this.regulatoryRiFunctionIdriFunction = regulatoryRiFunctionIdriFunction;
	}

	@Column(name = "regulatory_promoter_idpromoter", nullable = false)
	public int getRegulatoryPromoterIdpromoter() {
		return this.regulatoryPromoterIdpromoter;
	}

	public void setRegulatoryPromoterIdpromoter(int regulatoryPromoterIdpromoter) {
		this.regulatoryPromoterIdpromoter = regulatoryPromoterIdpromoter;
	}

	@Column(name = "model_protein_idprotein", nullable = false)
	public int getModelProteinIdprotein() {
		return this.modelProteinIdprotein;
	}

	public void setModelProteinIdprotein(int modelProteinIdprotein) {
		this.modelProteinIdprotein = modelProteinIdprotein;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegulatoryEventId))
			return false;
		RegulatoryEventId castOther = (RegulatoryEventId) other;

		return (this.getRegulatoryRiFunctionIdriFunction() == castOther.getRegulatoryRiFunctionIdriFunction())
				&& (this.getRegulatoryPromoterIdpromoter() == castOther.getRegulatoryPromoterIdpromoter())
				&& (this.getModelProteinIdprotein() == castOther.getModelProteinIdprotein());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRegulatoryRiFunctionIdriFunction();
		result = 37 * result + this.getRegulatoryPromoterIdpromoter();
		result = 37 * result + this.getModelProteinIdprotein();
		return result;
	}

}
