package pt.uminho.ceb.biosystems.merlin.entities.regulatory;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import pt.uminho.ceb.biosystems.merlin.entities.model.ModelProtein;

/**
 * RegulatoryEvent generated by hbm2java
 */
@Entity
@Table(name = "regulatory_event")
public class RegulatoryEvent implements java.io.Serializable {

	private RegulatoryEventId id;
	private ModelProtein modelProtein;
	private RegulatoryPromoter regulatoryPromoter;
	private RegulatoryRiFunction regulatoryRiFunction;
	private BigDecimal bindingSitePosition;

	public RegulatoryEvent() {
	}

	public RegulatoryEvent(RegulatoryEventId id, ModelProtein modelProtein, RegulatoryPromoter regulatoryPromoter,
			RegulatoryRiFunction regulatoryRiFunction) {
		this.id = id;
		this.modelProtein = modelProtein;
		this.regulatoryPromoter = regulatoryPromoter;
		this.regulatoryRiFunction = regulatoryRiFunction;
	}

	public RegulatoryEvent(RegulatoryEventId id, ModelProtein modelProtein, RegulatoryPromoter regulatoryPromoter,
			RegulatoryRiFunction regulatoryRiFunction, BigDecimal bindingSitePosition) {
		this.id = id;
		this.modelProtein = modelProtein;
		this.regulatoryPromoter = regulatoryPromoter;
		this.regulatoryRiFunction = regulatoryRiFunction;
		this.bindingSitePosition = bindingSitePosition;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "regulatoryRiFunctionIdriFunction", column = @Column(name = "regulatory_ri_function_idri_function", nullable = false)),
			@AttributeOverride(name = "regulatoryPromoterIdpromoter", column = @Column(name = "regulatory_promoter_idpromoter", nullable = false)),
			@AttributeOverride(name = "modelProteinIdprotein", column = @Column(name = "model_protein_idprotein", nullable = false)) })
	public RegulatoryEventId getId() {
		return this.id;
	}

	public void setId(RegulatoryEventId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "model_protein_idprotein", nullable = false, insertable = false, updatable = false)
	public ModelProtein getModelProtein() {
		return this.modelProtein;
	}

	public void setModelProtein(ModelProtein modelProtein) {
		this.modelProtein = modelProtein;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regulatory_promoter_idpromoter", nullable = false, insertable = false, updatable = false)
	public RegulatoryPromoter getRegulatoryPromoter() {
		return this.regulatoryPromoter;
	}

	public void setRegulatoryPromoter(RegulatoryPromoter regulatoryPromoter) {
		this.regulatoryPromoter = regulatoryPromoter;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regulatory_ri_function_idri_function", nullable = false, insertable = false, updatable = false)
	public RegulatoryRiFunction getRegulatoryRiFunction() {
		return this.regulatoryRiFunction;
	}

	public void setRegulatoryRiFunction(RegulatoryRiFunction regulatoryRiFunction) {
		this.regulatoryRiFunction = regulatoryRiFunction;
	}

	@Column(name = "binding_site_position", precision = 15, scale = 6)
	public BigDecimal getBindingSitePosition() {
		return this.bindingSitePosition;
	}

	public void setBindingSitePosition(BigDecimal bindingSitePosition) {
		this.bindingSitePosition = bindingSitePosition;
	}

}
