package pt.uminho.ceb.biosystems.merlin.entities.regulatory;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegulatoryTranscriptionUnitPromoterId generated by hbm2java
 */
@Embeddable
public class RegulatoryTranscriptionUnitPromoterId implements java.io.Serializable {

	private int regulatoryTranscriptionUnitIdtranscriptionUnit;
	private int regulatoryPromoterIdpromoter;

	public RegulatoryTranscriptionUnitPromoterId() {
	}

	public RegulatoryTranscriptionUnitPromoterId(int regulatoryTranscriptionUnitIdtranscriptionUnit,
			int regulatoryPromoterIdpromoter) {
		this.regulatoryTranscriptionUnitIdtranscriptionUnit = regulatoryTranscriptionUnitIdtranscriptionUnit;
		this.regulatoryPromoterIdpromoter = regulatoryPromoterIdpromoter;
	}

	@Column(name = "regulatory_transcription_unit_idtranscription_unit", nullable = false)
	public int getRegulatoryTranscriptionUnitIdtranscriptionUnit() {
		return this.regulatoryTranscriptionUnitIdtranscriptionUnit;
	}

	public void setRegulatoryTranscriptionUnitIdtranscriptionUnit(int regulatoryTranscriptionUnitIdtranscriptionUnit) {
		this.regulatoryTranscriptionUnitIdtranscriptionUnit = regulatoryTranscriptionUnitIdtranscriptionUnit;
	}

	@Column(name = "regulatory_promoter_idpromoter", nullable = false)
	public int getRegulatoryPromoterIdpromoter() {
		return this.regulatoryPromoterIdpromoter;
	}

	public void setRegulatoryPromoterIdpromoter(int regulatoryPromoterIdpromoter) {
		this.regulatoryPromoterIdpromoter = regulatoryPromoterIdpromoter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegulatoryTranscriptionUnitPromoterId))
			return false;
		RegulatoryTranscriptionUnitPromoterId castOther = (RegulatoryTranscriptionUnitPromoterId) other;

		return (this.getRegulatoryTranscriptionUnitIdtranscriptionUnit() == castOther
				.getRegulatoryTranscriptionUnitIdtranscriptionUnit())
				&& (this.getRegulatoryPromoterIdpromoter() == castOther.getRegulatoryPromoterIdpromoter());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRegulatoryTranscriptionUnitIdtranscriptionUnit();
		result = 37 * result + this.getRegulatoryPromoterIdpromoter();
		return result;
	}

}
