package pt.uminho.ceb.biosystems.merlin.entities.annotation.enzymes;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnzymesAnnotationProductRankHasOrganismId generated by hbm2java
 */
@Embeddable
public class EnzymesAnnotationProductRankHasOrganismId implements java.io.Serializable {

	private int enzymesAnnotationProductRankSKey;
	private int enzymesAnnotationOrganismSKey;

	public EnzymesAnnotationProductRankHasOrganismId() {
	}

	public EnzymesAnnotationProductRankHasOrganismId(int enzymesAnnotationProductRankSKey,
			int enzymesAnnotationOrganismSKey) {
		this.enzymesAnnotationProductRankSKey = enzymesAnnotationProductRankSKey;
		this.enzymesAnnotationOrganismSKey = enzymesAnnotationOrganismSKey;
	}

	@Column(name = "enzymes_annotation_productRank_s_key", nullable = false)
	public int getEnzymesAnnotationProductRankSKey() {
		return this.enzymesAnnotationProductRankSKey;
	}

	public void setEnzymesAnnotationProductRankSKey(int enzymesAnnotationProductRankSKey) {
		this.enzymesAnnotationProductRankSKey = enzymesAnnotationProductRankSKey;
	}

	@Column(name = "enzymes_annotation_organism_s_key", nullable = false)
	public int getEnzymesAnnotationOrganismSKey() {
		return this.enzymesAnnotationOrganismSKey;
	}

	public void setEnzymesAnnotationOrganismSKey(int enzymesAnnotationOrganismSKey) {
		this.enzymesAnnotationOrganismSKey = enzymesAnnotationOrganismSKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnzymesAnnotationProductRankHasOrganismId))
			return false;
		EnzymesAnnotationProductRankHasOrganismId castOther = (EnzymesAnnotationProductRankHasOrganismId) other;

		return (this.getEnzymesAnnotationProductRankSKey() == castOther.getEnzymesAnnotationProductRankSKey())
				&& (this.getEnzymesAnnotationOrganismSKey() == castOther.getEnzymesAnnotationOrganismSKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEnzymesAnnotationProductRankSKey();
		result = 37 * result + this.getEnzymesAnnotationOrganismSKey();
		return result;
	}

}
