package pt.uminho.ceb.biosystems.merlin.entities.annotation.enzymes;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnzymesAnnotationHomologuesHasEcNumberId generated by hbm2java
 */
@Embeddable
public class EnzymesAnnotationHomologuesHasEcNumberId implements java.io.Serializable {

	private int ecNumberSKey;
	private int enzymesAnnotationHomologuesSKey;

	public EnzymesAnnotationHomologuesHasEcNumberId() {
	}

	public EnzymesAnnotationHomologuesHasEcNumberId(int ecNumberSKey, int enzymesAnnotationHomologuesSKey) {
		this.ecNumberSKey = ecNumberSKey;
		this.enzymesAnnotationHomologuesSKey = enzymesAnnotationHomologuesSKey;
	}

	@Column(name = "ecNumber_s_key", nullable = false)
	public int getEcNumberSKey() {
		return this.ecNumberSKey;
	}

	public void setEcNumberSKey(int ecNumberSKey) {
		this.ecNumberSKey = ecNumberSKey;
	}

	@Column(name = "enzymes_annotation_homologues_s_key", nullable = false)
	public int getEnzymesAnnotationHomologuesSKey() {
		return this.enzymesAnnotationHomologuesSKey;
	}

	public void setEnzymesAnnotationHomologuesSKey(int enzymesAnnotationHomologuesSKey) {
		this.enzymesAnnotationHomologuesSKey = enzymesAnnotationHomologuesSKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnzymesAnnotationHomologuesHasEcNumberId))
			return false;
		EnzymesAnnotationHomologuesHasEcNumberId castOther = (EnzymesAnnotationHomologuesHasEcNumberId) other;

		return (this.getEcNumberSKey() == castOther.getEcNumberSKey())
				&& (this.getEnzymesAnnotationHomologuesSKey() == castOther.getEnzymesAnnotationHomologuesSKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEcNumberSKey();
		result = 37 * result + this.getEnzymesAnnotationHomologuesSKey();
		return result;
	}

}
