package pt.uminho.ceb.biosystems.merlin.entities.annotation.enzymes;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * EnzymesAnnotationProductRankHasOrganism generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_productRank_has_organism")
public class EnzymesAnnotationProductRankHasOrganism implements java.io.Serializable {

	private EnzymesAnnotationProductRankHasOrganismId id;
	private EnzymesAnnotationOrganism enzymesAnnotationOrganism;
	private EnzymesAnnotationProductRank enzymesAnnotationProductRank;

	public EnzymesAnnotationProductRankHasOrganism() {
	}

	public EnzymesAnnotationProductRankHasOrganism(EnzymesAnnotationProductRankHasOrganismId id,
			EnzymesAnnotationOrganism enzymesAnnotationOrganism,
			EnzymesAnnotationProductRank enzymesAnnotationProductRank) {
		this.id = id;
		this.enzymesAnnotationOrganism = enzymesAnnotationOrganism;
		this.enzymesAnnotationProductRank = enzymesAnnotationProductRank;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "enzymesAnnotationProductRankSKey", column = @Column(name = "enzymes_annotation_productRank_s_key", nullable = false)),
			@AttributeOverride(name = "enzymesAnnotationOrganismSKey", column = @Column(name = "enzymes_annotation_organism_s_key", nullable = false)) })
	public EnzymesAnnotationProductRankHasOrganismId getId() {
		return this.id;
	}

	public void setId(EnzymesAnnotationProductRankHasOrganismId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enzymes_annotation_organism_s_key", nullable = false, insertable = false, updatable = false)
	public EnzymesAnnotationOrganism getEnzymesAnnotationOrganism() {
		return this.enzymesAnnotationOrganism;
	}

	public void setEnzymesAnnotationOrganism(EnzymesAnnotationOrganism enzymesAnnotationOrganism) {
		this.enzymesAnnotationOrganism = enzymesAnnotationOrganism;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enzymes_annotation_productRank_s_key", nullable = false, insertable = false, updatable = false)
	public EnzymesAnnotationProductRank getEnzymesAnnotationProductRank() {
		return this.enzymesAnnotationProductRank;
	}

	public void setEnzymesAnnotationProductRank(EnzymesAnnotationProductRank enzymesAnnotationProductRank) {
		this.enzymesAnnotationProductRank = enzymesAnnotationProductRank;
	}

}
