package pt.uminho.ceb.biosystems.merlin.entities.annotation.enzymes;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * EnzymesAnnotationEcNumber generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_ecNumber")
@XmlRootElement( name = "ENZYMESANNOTATIONECNUMBER" )
public class EnzymesAnnotationEcNumber implements java.io.Serializable {

	private int SKey;
	private String ecNumber;
	private Set<EnzymesAnnotationHomologuesHasEcNumber> enzymesAnnotationHomologuesHasEcNumbers = new HashSet<EnzymesAnnotationHomologuesHasEcNumber>(
			0);

	public EnzymesAnnotationEcNumber() {
	}

	public EnzymesAnnotationEcNumber(int SKey) {
		this.SKey = SKey;
	}

	public EnzymesAnnotationEcNumber(int SKey, String ecNumber,
			Set<EnzymesAnnotationHomologuesHasEcNumber> enzymesAnnotationHomologuesHasEcNumbers) {
		this.SKey = SKey;
		this.ecNumber = ecNumber;
		this.enzymesAnnotationHomologuesHasEcNumbers = enzymesAnnotationHomologuesHasEcNumbers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "s_key", unique = true, nullable = false)
	@XmlElement( name = "SKEY" )
	public int getSKey() {
		return this.SKey;
	}

	public void setSKey(int SKey) {
		this.SKey = SKey;
	}

	@Column(name = "ecNumber", length = 16777215)
	@XmlElement( name = "ECNUMBER" )
	public String getEcNumber() {
		return this.ecNumber;
	}

	public void setEcNumber(String ecNumber) {
		this.ecNumber = ecNumber;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enzymesAnnotationEcNumber")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<EnzymesAnnotationHomologuesHasEcNumber> getEnzymesAnnotationHomologuesHasEcNumbers() {
		return this.enzymesAnnotationHomologuesHasEcNumbers;
	}

	public void setEnzymesAnnotationHomologuesHasEcNumbers(
			Set<EnzymesAnnotationHomologuesHasEcNumber> enzymesAnnotationHomologuesHasEcNumbers) {
		this.enzymesAnnotationHomologuesHasEcNumbers = enzymesAnnotationHomologuesHasEcNumbers;
	}

}
