package pt.uminho.ceb.biosystems.merlin.entities.annotation.enzymes;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * EnzymesAnnotationGeneHomologyHasHomologues generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_geneHomology_has_homologues")
public class EnzymesAnnotationGeneHomologyHasHomologues implements java.io.Serializable {

	private EnzymesAnnotationGeneHomologyHasHomologuesId id;
	private EnzymesAnnotationGeneHomology enzymesAnnotationGeneHomology;
	private EnzymesAnnotationHomologues enzymesAnnotationHomologues;
	private String referenceId;
	private String gene;
	private Float evalue;
	private Float bits;

	public EnzymesAnnotationGeneHomologyHasHomologues() {
	}

	public EnzymesAnnotationGeneHomologyHasHomologues(EnzymesAnnotationGeneHomologyHasHomologuesId id,
			EnzymesAnnotationGeneHomology enzymesAnnotationGeneHomology,
			EnzymesAnnotationHomologues enzymesAnnotationHomologues) {
		this.id = id;
		this.enzymesAnnotationGeneHomology = enzymesAnnotationGeneHomology;
		this.enzymesAnnotationHomologues = enzymesAnnotationHomologues;
	}

	public EnzymesAnnotationGeneHomologyHasHomologues(EnzymesAnnotationGeneHomologyHasHomologuesId id,
			EnzymesAnnotationGeneHomology enzymesAnnotationGeneHomology,
			EnzymesAnnotationHomologues enzymesAnnotationHomologues, String referenceId, String gene, Float evalue,
			Float bits) {
		this.id = id;
		this.enzymesAnnotationGeneHomology = enzymesAnnotationGeneHomology;
		this.enzymesAnnotationHomologues = enzymesAnnotationHomologues;
		this.referenceId = referenceId;
		this.gene = gene;
		this.evalue = evalue;
		this.bits = bits;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "geneHomologySKey", column = @Column(name = "geneHomology_s_key", nullable = false)),
			@AttributeOverride(name = "homologuesSKey", column = @Column(name = "homologues_s_key", nullable = false)) })
	public EnzymesAnnotationGeneHomologyHasHomologuesId getId() {
		return this.id;
	}

	public void setId(EnzymesAnnotationGeneHomologyHasHomologuesId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "geneHomology_s_key", nullable = false, insertable = false, updatable = false)
	public EnzymesAnnotationGeneHomology getEnzymesAnnotationGeneHomology() {
		return this.enzymesAnnotationGeneHomology;
	}

	public void setEnzymesAnnotationGeneHomology(EnzymesAnnotationGeneHomology enzymesAnnotationGeneHomology) {
		this.enzymesAnnotationGeneHomology = enzymesAnnotationGeneHomology;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homologues_s_key", nullable = false, insertable = false, updatable = false)
	public EnzymesAnnotationHomologues getEnzymesAnnotationHomologues() {
		return this.enzymesAnnotationHomologues;
	}

	public void setEnzymesAnnotationHomologues(EnzymesAnnotationHomologues enzymesAnnotationHomologues) {
		this.enzymesAnnotationHomologues = enzymesAnnotationHomologues;
	}

	@Column(name = "referenceID", length = 100)
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "gene", length = 100)
	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	@Column(name = "eValue", precision = 12, scale = 0)
	public Float getEvalue() {
		return this.evalue;
	}

	public void setEvalue(Float evalue) {
		this.evalue = evalue;
	}

	@Column(name = "bits", precision = 12, scale = 0)
	public Float getBits() {
		return this.bits;
	}

	public void setBits(Float bits) {
		this.bits = bits;
	}

}
