package pt.uminho.ceb.biosystems.merlin.entities.annotation.enzymes;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * EnzymesAnnotationHomologuesHasEcNumber generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_homologues_has_ecNumber")
public class EnzymesAnnotationHomologuesHasEcNumber implements java.io.Serializable {

	private EnzymesAnnotationHomologuesHasEcNumberId id;
	private EnzymesAnnotationEcNumber enzymesAnnotationEcNumber;
	private EnzymesAnnotationHomologues enzymesAnnotationHomologues;

	public EnzymesAnnotationHomologuesHasEcNumber() {
	}

	public EnzymesAnnotationHomologuesHasEcNumber(EnzymesAnnotationHomologuesHasEcNumberId id,
			EnzymesAnnotationEcNumber enzymesAnnotationEcNumber,
			EnzymesAnnotationHomologues enzymesAnnotationHomologues) {
		this.id = id;
		this.enzymesAnnotationEcNumber = enzymesAnnotationEcNumber;
		this.enzymesAnnotationHomologues = enzymesAnnotationHomologues;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ecNumberSKey", column = @Column(name = "ecNumber_s_key", nullable = false)),
			@AttributeOverride(name = "enzymesAnnotationHomologuesSKey", column = @Column(name = "enzymes_annotation_homologues_s_key", nullable = false)) })
	public EnzymesAnnotationHomologuesHasEcNumberId getId() {
		return this.id;
	}

	public void setId(EnzymesAnnotationHomologuesHasEcNumberId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ecNumber_s_key", nullable = false, insertable = false, updatable = false)
	public EnzymesAnnotationEcNumber getEnzymesAnnotationEcNumber() {
		return this.enzymesAnnotationEcNumber;
	}

	public void setEnzymesAnnotationEcNumber(EnzymesAnnotationEcNumber enzymesAnnotationEcNumber) {
		this.enzymesAnnotationEcNumber = enzymesAnnotationEcNumber;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enzymes_annotation_homologues_s_key", nullable = false, insertable = false, updatable = false)
	public EnzymesAnnotationHomologues getEnzymesAnnotationHomologues() {
		return this.enzymesAnnotationHomologues;
	}

	public void setEnzymesAnnotationHomologues(EnzymesAnnotationHomologues enzymesAnnotationHomologues) {
		this.enzymesAnnotationHomologues = enzymesAnnotationHomologues;
	}

}
