package pt.uminho.ceb.biosystems.merlin.entities.annotation.enzymes;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnzymesAnnotationEcNumberRankHasOrganismId generated by hbm2java
 */
@Embeddable
public class EnzymesAnnotationEcNumberRankHasOrganismId implements java.io.Serializable {

	private int organismSKey;
	private int ecNumberRankSKey;

	public EnzymesAnnotationEcNumberRankHasOrganismId() {
	}

	public EnzymesAnnotationEcNumberRankHasOrganismId(int organismSKey, int ecNumberRankSKey) {
		this.organismSKey = organismSKey;
		this.ecNumberRankSKey = ecNumberRankSKey;
	}

	@Column(name = "organism_s_key", nullable = false)
	public int getOrganismSKey() {
		return this.organismSKey;
	}

	public void setOrganismSKey(int organismSKey) {
		this.organismSKey = organismSKey;
	}

	@Column(name = "ecNumberRank_s_key", nullable = false)
	public int getEcNumberRankSKey() {
		return this.ecNumberRankSKey;
	}

	public void setEcNumberRankSKey(int ecNumberRankSKey) {
		this.ecNumberRankSKey = ecNumberRankSKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnzymesAnnotationEcNumberRankHasOrganismId))
			return false;
		EnzymesAnnotationEcNumberRankHasOrganismId castOther = (EnzymesAnnotationEcNumberRankHasOrganismId) other;

		return (this.getOrganismSKey() == castOther.getOrganismSKey())
				&& (this.getEcNumberRankSKey() == castOther.getEcNumberRankSKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrganismSKey();
		result = 37 * result + this.getEcNumberRankSKey();
		return result;
	}

}
