package pt.uminho.ceb.biosystems.merlin.entities.annotation.enzymes;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * EnzymesAnnotationOrganism generated by hbm2java
 */
@Entity
@Table(name = "enzymes_annotation_organism")
public class EnzymesAnnotationOrganism implements java.io.Serializable {

	private int SKey;
	private String organism;
	private String taxonomy;
	private Integer taxRank;
	private Set<EnzymesAnnotationHomologues> enzymesAnnotationHomologueses = new HashSet<EnzymesAnnotationHomologues>(
			0);
	private Set<EnzymesAnnotationEcNumberRankHasOrganism> enzymesAnnotationEcNumberRankHasOrganisms = new HashSet<EnzymesAnnotationEcNumberRankHasOrganism>(
			0);
	private Set<EnzymesAnnotationProductRankHasOrganism> enzymesAnnotationProductRankHasOrganisms = new HashSet<EnzymesAnnotationProductRankHasOrganism>(
			0);

	public EnzymesAnnotationOrganism() {
	}

	public EnzymesAnnotationOrganism(int SKey) {
		this.SKey = SKey;
	}

	public EnzymesAnnotationOrganism(int SKey, String organism, String taxonomy, Integer taxRank,
			Set<EnzymesAnnotationHomologues> enzymesAnnotationHomologueses,
			Set<EnzymesAnnotationEcNumberRankHasOrganism> enzymesAnnotationEcNumberRankHasOrganisms,
			Set<EnzymesAnnotationProductRankHasOrganism> enzymesAnnotationProductRankHasOrganisms) {
		this.SKey = SKey;
		this.organism = organism;
		this.taxonomy = taxonomy;
		this.taxRank = taxRank;
		this.enzymesAnnotationHomologueses = enzymesAnnotationHomologueses;
		this.enzymesAnnotationEcNumberRankHasOrganisms = enzymesAnnotationEcNumberRankHasOrganisms;
		this.enzymesAnnotationProductRankHasOrganisms = enzymesAnnotationProductRankHasOrganisms;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "s_key", unique = true, nullable = false)
	public int getSKey() {
		return this.SKey;
	}

	public void setSKey(int SKey) {
		this.SKey = SKey;
	}

	@Column(name = "organism", length = 200)
	public String getOrganism() {
		return this.organism;
	}

	public void setOrganism(String organism) {
		this.organism = organism;
	}

	@Column(name = "taxonomy", length = 65535, columnDefinition="Text")
	public String getTaxonomy() {
		return this.taxonomy;
	}

	public void setTaxonomy(String taxonomy) {
		this.taxonomy = taxonomy;
	}

	@Column(name = "taxRank")
	public Integer getTaxRank() {
		return this.taxRank;
	}

	public void setTaxRank(Integer taxRank) {
		this.taxRank = taxRank;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enzymesAnnotationOrganism")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<EnzymesAnnotationHomologues> getEnzymesAnnotationHomologueses() {
		return this.enzymesAnnotationHomologueses;
	}

	public void setEnzymesAnnotationHomologueses(Set<EnzymesAnnotationHomologues> enzymesAnnotationHomologueses) {
		this.enzymesAnnotationHomologueses = enzymesAnnotationHomologueses;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enzymesAnnotationOrganism")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<EnzymesAnnotationEcNumberRankHasOrganism> getEnzymesAnnotationEcNumberRankHasOrganisms() {
		return this.enzymesAnnotationEcNumberRankHasOrganisms;
	}

	public void setEnzymesAnnotationEcNumberRankHasOrganisms(
			Set<EnzymesAnnotationEcNumberRankHasOrganism> enzymesAnnotationEcNumberRankHasOrganisms) {
		this.enzymesAnnotationEcNumberRankHasOrganisms = enzymesAnnotationEcNumberRankHasOrganisms;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enzymesAnnotationOrganism")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<EnzymesAnnotationProductRankHasOrganism> getEnzymesAnnotationProductRankHasOrganisms() {
		return this.enzymesAnnotationProductRankHasOrganisms;
	}

	public void setEnzymesAnnotationProductRankHasOrganisms(
			Set<EnzymesAnnotationProductRankHasOrganism> enzymesAnnotationProductRankHasOrganisms) {
		this.enzymesAnnotationProductRankHasOrganisms = enzymesAnnotationProductRankHasOrganisms;
	}

}
