package pt.uminho.ceb.biosystems.merlin.entities.interpro;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * InterproModel generated by hbm2java
 */
@Entity
@Table(name = "interpro_model")
public class InterproModel implements java.io.Serializable {

	private String accession;
	private String description;
	private String name;
	private Set<InterproResultHasModel> interproResultHasModels = new HashSet<InterproResultHasModel>(0);

	public InterproModel() {
	}

	public InterproModel(String accession) {
		this.accession = accession;
	}

	public InterproModel(String accession, String description, String name,
			Set<InterproResultHasModel> interproResultHasModels) {
		this.accession = accession;
		this.description = description;
		this.name = name;
		this.interproResultHasModels = interproResultHasModels;
	}

	@Id

	@Column(name = "accession", unique = true, nullable = false, length = 45)
	public String getAccession() {
		return this.accession;
	}

	public void setAccession(String accession) {
		this.accession = accession;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "interproModel")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<InterproResultHasModel> getInterproResultHasModels() {
		return this.interproResultHasModels;
	}

	public void setInterproResultHasModels(Set<InterproResultHasModel> interproResultHasModels) {
		this.interproResultHasModels = interproResultHasModels;
	}

}
