package pt.uminho.ceb.biosystems.merlin.entities.interpro;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * InterproResultHasEntry generated by hbm2java
 */
@Entity
@Table(name = "interpro_result_has_entry")
public class InterproResultHasEntry implements java.io.Serializable {

	private InterproResultHasEntryId id;
	private InterproEntry interproEntry;
	private InterproResult interproResult;

	public InterproResultHasEntry() {
	}

	public InterproResultHasEntry(InterproResultHasEntryId id, InterproEntry interproEntry,
			InterproResult interproResult) {
		this.id = id;
		this.interproEntry = interproEntry;
		this.interproResult = interproResult;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "interproResultId", column = @Column(name = "interpro_result_id", nullable = false)),
			@AttributeOverride(name = "interproEntryId", column = @Column(name = "interpro_entry_id", nullable = false)) })
	public InterproResultHasEntryId getId() {
		return this.id;
	}

	public void setId(InterproResultHasEntryId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interpro_entry_id", nullable = false, insertable = false, updatable = false)
	public InterproEntry getInterproEntry() {
		return this.interproEntry;
	}

	public void setInterproEntry(InterproEntry interproEntry) {
		this.interproEntry = interproEntry;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interpro_result_id", nullable = false, insertable = false, updatable = false)
	public InterproResult getInterproResult() {
		return this.interproResult;
	}

	public void setInterproResult(InterproResult interproResult) {
		this.interproResult = interproResult;
	}

}
