package pt.uminho.ceb.biosystems.merlin.entities.interpro;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * InterproEntry generated by hbm2java
 */
@Entity
@Table(name = "interpro_entry")
public class InterproEntry implements java.io.Serializable {

	private int id;
	private String accession;
	private String description;
	private String name;
	private String type;
	private Set<InterproXRef> interproXRefs = new HashSet<InterproXRef>(0);
	private Set<InterproResultHasEntry> interproResultHasEntries = new HashSet<InterproResultHasEntry>(0);

	public InterproEntry() {
	}

	public InterproEntry(int id, String accession, String description, String name, String type) {
		this.id = id;
		this.accession = accession;
		this.description = description;
		this.name = name;
		this.type = type;
	}

	public InterproEntry(int id, String accession, String description, String name, String type,
			Set<InterproXRef> interproXRefs, Set<InterproResultHasEntry> interproResultHasEntries) {
		this.id = id;
		this.accession = accession;
		this.description = description;
		this.name = name;
		this.type = type;
		this.interproXRefs = interproXRefs;
		this.interproResultHasEntries = interproResultHasEntries;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "accession", nullable = false, length = 45)
	public String getAccession() {
		return this.accession;
	}

	public void setAccession(String accession) {
		this.accession = accession;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "interproEntry")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<InterproXRef> getInterproXRefs() {
		return this.interproXRefs;
	}

	public void setInterproXRefs(Set<InterproXRef> interproXRefs) {
		this.interproXRefs = interproXRefs;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "interproEntry")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<InterproResultHasEntry> getInterproResultHasEntries() {
		return this.interproResultHasEntries;
	}

	public void setInterproResultHasEntries(Set<InterproResultHasEntry> interproResultHasEntries) {
		this.interproResultHasEntries = interproResultHasEntries;
	}

}
