package pt.uminho.ceb.biosystems.merlin.entities.interpro;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * InterproResults generated by hbm2java
 */
@Entity
@Table(name = "interpro_results")
public class InterproResults implements java.io.Serializable {

	private int id;
	private String query;
	private String querySequence;
	private String mostLikelyEc;
	private String mostLikelyLocalization;
	private String mostLikelyName;
	private String status;
	private Set<InterproResult> interproResults = new HashSet<InterproResult>(0);

	public InterproResults() {
	}

	public InterproResults(int id, String query, String querySequence) {
		this.id = id;
		this.query = query;
		this.querySequence = querySequence;
	}

	public InterproResults(int id, String query, String querySequence, String mostLikelyEc,
			String mostLikelyLocalization, String mostLikelyName, String status, Set<InterproResult> interproResults) {
		this.id = id;
		this.query = query;
		this.querySequence = querySequence;
		this.mostLikelyEc = mostLikelyEc;
		this.mostLikelyLocalization = mostLikelyLocalization;
		this.mostLikelyName = mostLikelyName;
		this.status = status;
		this.interproResults = interproResults;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "query", nullable = false, length = 45)
	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	@Column(name = "querySequence", nullable = false)
	public String getQuerySequence() {
		return this.querySequence;
	}

	public void setQuerySequence(String querySequence) {
		this.querySequence = querySequence;
	}

	@Column(name = "mostLikelyEc", length = 45)
	public String getMostLikelyEc() {
		return this.mostLikelyEc;
	}

	public void setMostLikelyEc(String mostLikelyEc) {
		this.mostLikelyEc = mostLikelyEc;
	}

	@Column(name = "mostLikelyLocalization", length = 45)
	public String getMostLikelyLocalization() {
		return this.mostLikelyLocalization;
	}

	public void setMostLikelyLocalization(String mostLikelyLocalization) {
		this.mostLikelyLocalization = mostLikelyLocalization;
	}

	@Column(name = "mostLikelyName", length = 250)
	public String getMostLikelyName() {
		return this.mostLikelyName;
	}

	public void setMostLikelyName(String mostLikelyName) {
		this.mostLikelyName = mostLikelyName;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "interproResults")
	@OnDelete(action = OnDeleteAction.CASCADE)
	public Set<InterproResult> getInterproResults() {
		return this.interproResults;
	}

	public void setInterproResults(Set<InterproResult> interproResults) {
		this.interproResults = interproResults;
	}

}
