package pt.uminho.ceb.biosystems.merlin.entities.interpro;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * InterproLocation generated by hbm2java
 */
@Entity
@Table(name = "interpro_location")
public class InterproLocation implements java.io.Serializable {

	private int id;
	private InterproResult interproResult;
	private int start;
	private int end;
	private Float score;
	private Integer hmmStart;
	private Integer hmmEnd;
	private Float evalue;
	private Integer envStart;
	private Integer envEnd;
	private Integer hmmLength;

	public InterproLocation() {
	}

	public InterproLocation(int id, InterproResult interproResult, int start, int end) {
		this.id = id;
		this.interproResult = interproResult;
		this.start = start;
		this.end = end;
	}

	public InterproLocation(int id, InterproResult interproResult, int start, int end, Float score, Integer hmmStart,
			Integer hmmEnd, Float evalue, Integer envStart, Integer envEnd, Integer hmmLength) {
		this.id = id;
		this.interproResult = interproResult;
		this.start = start;
		this.end = end;
		this.score = score;
		this.hmmStart = hmmStart;
		this.hmmEnd = hmmEnd;
		this.evalue = evalue;
		this.envStart = envStart;
		this.envEnd = envEnd;
		this.hmmLength = hmmLength;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator="UseExistingIdOtherwiseGenerateUsingIdentity")
	@GenericGenerator(name = "UseExistingIdOtherwiseGenerateUsingIdentity", strategy = "pt.uminho.ceb.biosystems.merlin.auxiliary.UseExistingIdOtherwiseGenerateUsingIdentity")	
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interpro_result_id", nullable = false)
	public InterproResult getInterproResult() {
		return this.interproResult;
	}

	public void setInterproResult(InterproResult interproResult) {
		this.interproResult = interproResult;
	}

	@Column(name = "start", nullable = false)
	public int getStart() {
		return this.start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	@Column(name = "end", nullable = false)
	public int getEnd() {
		return this.end;
	}

	public void setEnd(int end) {
		this.end = end;
	}

	@Column(name = "score", precision = 12, scale = 0)
	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	@Column(name = "hmmStart")
	public Integer getHmmStart() {
		return this.hmmStart;
	}

	public void setHmmStart(Integer hmmStart) {
		this.hmmStart = hmmStart;
	}

	@Column(name = "hmmEnd")
	public Integer getHmmEnd() {
		return this.hmmEnd;
	}

	public void setHmmEnd(Integer hmmEnd) {
		this.hmmEnd = hmmEnd;
	}

	@Column(name = "eValue", precision = 12, scale = 0)
	public Float getEvalue() {
		return this.evalue;
	}

	public void setEvalue(Float evalue) {
		this.evalue = evalue;
	}

	@Column(name = "envStart")
	public Integer getEnvStart() {
		return this.envStart;
	}

	public void setEnvStart(Integer envStart) {
		this.envStart = envStart;
	}

	@Column(name = "envEnd")
	public Integer getEnvEnd() {
		return this.envEnd;
	}

	public void setEnvEnd(Integer envEnd) {
		this.envEnd = envEnd;
	}

	@Column(name = "hmmLength")
	public Integer getHmmLength() {
		return this.hmmLength;
	}

	public void setHmmLength(Integer hmmLength) {
		this.hmmLength = hmmLength;
	}

}
