package pt.uminho.ceb.biosystems.merlin.entities.interpro;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * InterproResultHasModel generated by hbm2java
 */
@Entity
@Table(name = "interpro_result_has_model")
public class InterproResultHasModel implements java.io.Serializable {

	private InterproResultHasModelId id;
	private InterproModel interproModel;
	private InterproResult interproResult;

	public InterproResultHasModel() {
	}

	public InterproResultHasModel(InterproResultHasModelId id, InterproModel interproModel,
			InterproResult interproResult) {
		this.id = id;
		this.interproModel = interproModel;
		this.interproResult = interproResult;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "interproResultId", column = @Column(name = "interpro_result_id", nullable = false)),
			@AttributeOverride(name = "interproModelAccession", column = @Column(name = "interpro_model_accession", nullable = false, length = 45)) })
	public InterproResultHasModelId getId() {
		return this.id;
	}

	public void setId(InterproResultHasModelId id) {
		this.id = id;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interpro_model_accession", nullable = false, insertable = false, updatable = false)
	public InterproModel getInterproModel() {
		return this.interproModel;
	}

	public void setInterproModel(InterproModel interproModel) {
		this.interproModel = interproModel;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "interpro_result_id", nullable = false, insertable = false, updatable = false)
	public InterproResult getInterproResult() {
		return this.interproResult;
	}

	public void setInterproResult(InterproResult interproResult) {
		this.interproResult = interproResult;
	}

}
