package pt.uminho.ceb.biosystems.merlin.entities.interpro;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InterproResultHasModelId generated by hbm2java
 */
@Embeddable
public class InterproResultHasModelId implements java.io.Serializable {

	private int interproResultId;
	private String interproModelAccession;

	public InterproResultHasModelId() {
	}

	public InterproResultHasModelId(int interproResultId, String interproModelAccession) {
		this.interproResultId = interproResultId;
		this.interproModelAccession = interproModelAccession;
	}

	@Column(name = "interpro_result_id", nullable = false)
	public int getInterproResultId() {
		return this.interproResultId;
	}

	public void setInterproResultId(int interproResultId) {
		this.interproResultId = interproResultId;
	}

	@Column(name = "interpro_model_accession", nullable = false, length = 45)
	public String getInterproModelAccession() {
		return this.interproModelAccession;
	}

	public void setInterproModelAccession(String interproModelAccession) {
		this.interproModelAccession = interproModelAccession;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InterproResultHasModelId))
			return false;
		InterproResultHasModelId castOther = (InterproResultHasModelId) other;

		return (this.getInterproResultId() == castOther.getInterproResultId())
				&& ((this.getInterproModelAccession() == castOther.getInterproModelAccession())
						|| (this.getInterproModelAccession() != null && castOther.getInterproModelAccession() != null
								&& this.getInterproModelAccession().equals(castOther.getInterproModelAccession())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInterproResultId();
		result = 37 * result + (getInterproModelAccession() == null ? 0 : this.getInterproModelAccession().hashCode());
		return result;
	}

}
