package pt.uminho.ceb.biosystems.merlin.entities.interpro;
// Generated Jul 16, 2019 10:41:08 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InterproResultHasEntryId generated by hbm2java
 */
@Embeddable
public class InterproResultHasEntryId implements java.io.Serializable {

	private int interproResultId;
	private int interproEntryId;

	public InterproResultHasEntryId() {
	}

	public InterproResultHasEntryId(int interproResultId, int interproEntryId) {
		this.interproResultId = interproResultId;
		this.interproEntryId = interproEntryId;
	}

	@Column(name = "interpro_result_id", nullable = false)
	public int getInterproResultId() {
		return this.interproResultId;
	}

	public void setInterproResultId(int interproResultId) {
		this.interproResultId = interproResultId;
	}

	@Column(name = "interpro_entry_id", nullable = false)
	public int getInterproEntryId() {
		return this.interproEntryId;
	}

	public void setInterproEntryId(int interproEntryId) {
		this.interproEntryId = interproEntryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InterproResultHasEntryId))
			return false;
		InterproResultHasEntryId castOther = (InterproResultHasEntryId) other;

		return (this.getInterproResultId() == castOther.getInterproResultId())
				&& (this.getInterproEntryId() == castOther.getInterproEntryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInterproResultId();
		result = 37 * result + this.getInterproEntryId();
		return result;
	}

}
